/* @date 2026-07-01T10:15:55.180400900Z */

/**********************************************************************************
 * @file Context_Interaction_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 **********************************************************************************/

#ifndef CONTEXT_INTERACTION_ITF_H
#define CONTEXT_INTERACTION_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Context_Interaction_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/**
	 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
	 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3	
	 */
	void (*Write_p1_modeSelected)(Integer* data);

	/**
	 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9	
	 */
	void (*Write_p2_doorPosition)(Integer* data);

	/* Trigger functions */

	/**
	 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Trigger_p1_door_status_change_signal)(void);

	/**
	 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Trigger_p1_mode_change_signal)(void);

	/**
	 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Trigger_p2_door_status_change_signal)(void);

	/**
	 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Trigger_p2_mode_change_signal)(void);

	/**
	 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Trigger_p2_execution_completed)(void);

	/* Read functions */

	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 */
	void (*Read_p3_doorPosition)(Integer* data);

	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Read_p3_door_status_change_signal)(SignalEvent_door_status_change_signal_type* data);

	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Read_p3_mode_change_signal)(SignalEvent_mode_change_signal_type* data);

	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Read_p3_execution_completed)(SignalEvent_execution_completed_type* data);

	/**
	 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
	 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
	 */
	void (*Read_p7_responseComputed)(Integer* data);

	/**
	 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Read_p7_execution_completed)(SignalEvent_execution_completed_type* data);

	/* Server call functions */

	/* pointer to parent */
	struct Context_Interaction_ *parent;
} Cse_Context_Interaction_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

/** @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de */
void Context_Interaction_Context_Interaction_init(Cse_Context_Interaction_Struct* instance);
void Context_Interaction_Context_Interaction_main(Cse_Context_Interaction_Struct* instance);
void Context_Interaction_Context_Interaction_end(Cse_Context_Interaction_Struct* instance);

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/**
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_Write_p1_modeSelected(Cse_Context_Interaction_Struct* instance, Integer* data);

/**
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Write_p2_doorPosition(Cse_Context_Interaction_Struct* instance, Integer* data);

/* Trigger functions declaration */

/**
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_p1_door_status_change_signal(Cse_Context_Interaction_Struct* instance);

/**
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_p1_mode_change_signal(Cse_Context_Interaction_Struct* instance);

/**
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_p2_door_status_change_signal(Cse_Context_Interaction_Struct* instance);

/**
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_p2_mode_change_signal(Cse_Context_Interaction_Struct* instance);

/**
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_p2_execution_completed(Cse_Context_Interaction_Struct* instance);

/* Read functions declaration */

/**
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Read_p3_doorPosition(Cse_Context_Interaction_Struct* instance, Integer* data);

/**
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Read_p3_door_status_change_signal(Cse_Context_Interaction_Struct* instance, SignalEvent_door_status_change_signal_type* data);

/**
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Read_p3_mode_change_signal(Cse_Context_Interaction_Struct* instance, SignalEvent_mode_change_signal_type* data);

/**
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Read_p3_execution_completed(Cse_Context_Interaction_Struct* instance, SignalEvent_execution_completed_type* data);

/**
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_Read_p7_responseComputed(Cse_Context_Interaction_Struct* instance, Integer* data);

/**
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Read_p7_execution_completed(Cse_Context_Interaction_Struct* instance, SignalEvent_execution_completed_type* data);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Write_p1_modeSelected(inst, data) (inst)->Write_p1_modeSelected(data)
#define Cse_Write_p2_doorPosition(inst, data) (inst)->Write_p2_doorPosition(data)
#define Cse_Trigger_p1_door_status_change_signal(inst) (inst)->Trigger_p1_door_status_change_signal()
#define Cse_Trigger_p1_mode_change_signal(inst) (inst)->Trigger_p1_mode_change_signal()
#define Cse_Trigger_p2_door_status_change_signal(inst) (inst)->Trigger_p2_door_status_change_signal()
#define Cse_Trigger_p2_mode_change_signal(inst) (inst)->Trigger_p2_mode_change_signal()
#define Cse_Trigger_p2_execution_completed(inst) (inst)->Trigger_p2_execution_completed()
#define Cse_Read_p3_doorPosition(inst, data) (inst)->Read_p3_doorPosition(data)
#define Cse_Read_p3_door_status_change_signal(inst, data) (inst)->Read_p3_door_status_change_signal(data)
#define Cse_Read_p3_mode_change_signal(inst, data) (inst)->Read_p3_mode_change_signal(data)
#define Cse_Read_p3_execution_completed(inst, data) (inst)->Read_p3_execution_completed(data)
#define Cse_Read_p7_responseComputed(inst, data) (inst)->Read_p7_responseComputed(data)
#define Cse_Read_p7_execution_completed(inst, data) (inst)->Read_p7_execution_completed(data)
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* CONTEXT_INTERACTION_ITF_H */

/* end of file */