/* @date 2026-07-01T10:15:55.133040200Z */

/**********************************************************************************
 * @file Context_Interaction_Context_Interaction_door_status_change_signal.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 * @reverse_ignore
 **********************************************************************************/

#ifndef CONTEXT_INTERACTION_CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_H
#define CONTEXT_INTERACTION_CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_H

#include "Context_Interaction_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_NO_EVENT,
    CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_door_status_change_signal
} CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T;

#ifndef ESP_TYPES_Context_Interaction_door_status_change_signal
#define ESP_TYPES_Context_Interaction_door_status_change_signal
typedef double  WALLCLOCK_T_Context_Interaction_door_status_change_signal;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_Context_Interaction_door_status_change_signal;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct Context_Interaction_door_status_change_signal_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Context_Interaction_door_status_change_signal_struct_*);

    /* user data */
    USERDATA_T_Context_Interaction_door_status_change_signal    USERDATA;

    /* data */

    Integer                                                     p1_modeSelected;
    Integer                                                     p2_doorPosition;
    Integer                                                     p3_doorPosition;
    Integer                                                     p7_responseComputed;



    /* events */
    CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T       EVENT;
    CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T       (*peekEVENT)(const struct Context_Interaction_door_status_change_signal_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T       (*nextEVENT)(struct Context_Interaction_door_status_change_signal_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                     (*sendEVENT)(struct Context_Interaction_door_status_change_signal_struct_ \
        *instance, CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct Context_Interaction_* classifier;

    /* internal */
    uint32_t                                                    flow[1];

    WALLCLOCK_T_Context_Interaction_door_status_change_signal   WALL_CLOCK;
} Context_Interaction_door_status_change_signal_struct;

void Context_Interaction_door_status_change_signal_struct_ctor(struct Context_Interaction_door_status_change_signal_struct_ \
    * const self, struct Context_Interaction_* classifier);
void basic_Context_Interaction_door_status_change_signal_init(Context_Interaction_door_status_change_signal_struct *instance);
Boolean basic_Context_Interaction_door_status_change_signal(Context_Interaction_door_status_change_signal_struct *instance);
void basic_Context_Interaction_door_status_change_signal_end(Context_Interaction_door_status_change_signal_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*CONTEXT_INTERACTION_CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_H*/
/* end of file */
