/* @date 2026-07-01T10:15:55.171865200Z */

/**********************************************************************************
 * @file Context_Interaction_type.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 **********************************************************************************/

#ifndef CONTEXT_INTERACTION_TYPE_H
#define CONTEXT_INTERACTION_TYPE_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h>

/* stdbool.h define standard bool (true/false) starting from C99 standard */
#include <stdbool.h>

/**********************************************************************************
 * Data Type Integer definition
 **********************************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;    
#endif /* Integer */

/**********************************************************************************
 * Data Type trigger_type definition
 **********************************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;    
#endif /* trigger_type */

/**********************************************************************************
 * Data Type SignalEvent_door_status_change_signal_type definition
 **********************************************************************************/
#ifndef SignalEvent_door_status_change_signal_type_DEFINITION
#define SignalEvent_door_status_change_signal_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_door_status_change_signal_type;    
#endif /* SignalEvent_door_status_change_signal_type */

/**********************************************************************************
 * Data Type SignalEvent_mode_change_signal_type definition
 **********************************************************************************/
#ifndef SignalEvent_mode_change_signal_type_DEFINITION
#define SignalEvent_mode_change_signal_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_mode_change_signal_type;    
#endif /* SignalEvent_mode_change_signal_type */

/**********************************************************************************
 * Data Type SignalEvent_execution_completed_type definition
 **********************************************************************************/
#ifndef SignalEvent_execution_completed_type_DEFINITION
#define SignalEvent_execution_completed_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_execution_completed_type;    
#endif /* SignalEvent_execution_completed_type */

#endif /* CONTEXT_INTERACTION_TYPE_H */

/* end of file */