/* @date 2026-07-01T10:15:55.067497900Z */

/**********************************************************************************
 * @file Context_Interaction_Context_Interaction.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 * @reverse_ignore
 **********************************************************************************/

#ifndef CONTEXT_INTERACTION_CONTEXT_INTERACTION_H
#define CONTEXT_INTERACTION_CONTEXT_INTERACTION_H

#include <stdint.h>
#include "Context_Interaction_itf.h" /* Datatypes defined at interfaces */
#include "internal_types.h" /* Datatypes for internal data */

#include "Context_Interaction_Context_Interaction_door_status_change_signal.h"
#include "Context_Interaction_Context_Interaction_mode_change_signal.h"

#ifndef WALLCLOCK_T_Context_Interaction
#define WALLCLOCK_T_Context_Interaction WALLCLOCK_T_Context_Interaction
typedef double  WALLCLOCK_T_Context_Interaction;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T_Context_Interaction
#define USERDATA_T_Context_Interaction  USERDATA_T_Context_Interaction
typedef void *  USERDATA_T_Context_Interaction;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef enum {
    CONTEXT_INTERACTION_STATE_T_INITIAL_0,
    CONTEXT_INTERACTION_STATE_T_maint,
    CONTEXT_INTERACTION_STATE_T_mode_change,
    CONTEXT_INTERACTION_STATE_T_idle,
    CONTEXT_INTERACTION_STATE_T_GO,
    CONTEXT_INTERACTION_STATE_T_Open,
    CONTEXT_INTERACTION_STATE_T_Close,
    CONTEXT_INTERACTION_STATE_T_request_sent,
    CONTEXT_INTERACTION_STATE_T_door_status_change,
    CONTEXT_INTERACTION_STATE_T_VOID
} CONTEXT_INTERACTION_STATE_T;

typedef enum {
    CONTEXT_INTERACTION_EVENT_T_execution_completed,
    CONTEXT_INTERACTION_EVENT_T_NO_EVENT
} CONTEXT_INTERACTION_EVENT_T;

typedef struct Context_Interaction_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct Context_Interaction_struct*);

    /* user data */
    USERDATA_T_Context_Interaction                          USERDATA;


    /* data */
    Integer                                                 p1_modeSelected;
    Integer                                                 p2_doorPosition;
    Integer                                                 p3_doorPosition;
    Integer                                                 p7_responseComputed;


    /* sub behaviors */
    Context_Interaction_door_status_change_signal_struct    door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal;
    Context_Interaction_mode_change_signal_struct           mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal;

    /* pointer to classifier */
    struct Context_Interaction_                         *   classifier;

    /* Region states */
    CONTEXT_INTERACTION_STATE_T                             CURRENT_STATE_0;

    /* Main clock */
    WALLCLOCK_T_Context_Interaction                         WALL_CLOCK;

    CONTEXT_INTERACTION_EVENT_T                             EVENT;
    Boolean                                                 FIRST;
    Boolean                                                 DONE_ACTIVITY;
} Context_Interaction_struct;

/**********************************************************************************
 * Function Context_Interaction_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void Context_Interaction_struct_ctor(struct Context_Interaction_struct * const self, struct Context_Interaction_* classifier);

/**********************************************************************************
 * Function basic_Context_Interaction_init
 * Implements statemachine init code
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction_init(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function basic_Context_Interaction
 * Implements statemachine main loop
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function basic_Context_Interaction_end
 * Implements statemachine exit code
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction_end(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function Close_Entry
 * Implements "Entry" of State: Close
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e1b913da-e022-41cc-956e-057612b93655
 * @generated_from b46fcf6e-48e2-4f98-8cfe-a70a2228a72d
 **********************************************************************************/
void Context_Interaction_Close_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function GO_Entry
 * Implements "Entry" of State: GO
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 1c1ea3f0-eaad-40f7-9352-50a54f20d2b7
 * @generated_from 82a00b74-7f3c-4181-a148-5dcb08d66a29
 **********************************************************************************/
void Context_Interaction_GO_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function Open_Entry
 * Implements "Entry" of State: Open
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 01aeb3b6-59ca-48f1-89ce-f6a52d3f8206
 * @generated_from cc28478c-6591-4bd9-b30a-a4f0d4d63c7c
 **********************************************************************************/
void Context_Interaction_Open_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function door_status_change_Entry
 * Implements "Entry" of State: door status change
 * Entry calls Activity: door status change signal
 *
 * @generated_from 94ded1b0-ba11-4616-aa3d-7f016ca0d728
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
void Context_Interaction_door_status_change_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function idle_Entry
 * Implements "Entry" of State: idle
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e6e54d5c-74f2-4f73-9b55-0b17a61e32c8
 * @generated_from cf23e36b-943e-431d-b64d-4f8a2c2a9768
 **********************************************************************************/
void Context_Interaction_idle_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function maint_Entry
 * Implements "Entry" of State: maint
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 534195b5-15dd-4955-bae1-6dccb26f9d77
 * @generated_from e573cf0c-e673-413a-b727-9d5011bef19e
 **********************************************************************************/
void Context_Interaction_maint_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * Function mode_change_Entry
 * Implements "Entry" of State: mode change
 * Entry calls Activity: mode change signal
 *
 * @generated_from 460408d9-eb18-4f88-ab8b-17dfc320f0a7
 * @generated_from ecd03eac-9979-4c36-bc22-ea38b76a2ea8
 **********************************************************************************/
void Context_Interaction_mode_change_Entry_1(Context_Interaction_struct *instance);

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void Context_Interaction_user_init(Context_Interaction_struct *instance);

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void Context_Interaction_user_end(Context_Interaction_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*CONTEXT_INTERACTION_CONTEXT_INTERACTION_H*/
/* end of file */
