/* @date 2026-07-01T10:15:55.170712100Z */

/**********************************************************************************
 * @file Context_Interaction_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 **********************************************************************************/

#include "Context_Interaction.h"
#include "Context_Interaction_itf.h"
#include "Context_Interaction_Context_Interaction.h"
#include "Tal.h" // tal_getTime

/**********************************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************************/
void Context_Interaction_Context_Interaction_init(Cse_Context_Interaction_Struct* instance) {
    /* Get component Context Interaction from "parent" */
    Context_Interaction *pContext_Interaction = instance->parent;

    /* Get behavior context_Interaction_Context_Interaction from the Context Interaction */
    Context_Interaction_struct *context_Interaction_Context_Interaction = &pContext_Interaction->Context_Interaction_Context_Interaction;


    /* Initialization job which can be done in a separated function or inlined. */
    basic_Context_Interaction_init(context_Interaction_Context_Interaction);
}

/**********************************************************************************
 * Main function Body of behavior "Context_Interaction_Context_Interaction"
 **********************************************************************************/
void Context_Interaction_Context_Interaction_main(Cse_Context_Interaction_Struct* instance) {
    /* Get component Context Interaction from "parent" */
    Context_Interaction *pContext_Interaction = instance->parent;

    /* Get behavior context_Interaction_Context_Interaction from the Context Interaction */
    Context_Interaction_struct *context_Interaction_Context_Interaction = &pContext_Interaction->Context_Interaction_Context_Interaction;

    /* read input(s) */
    Cse_Read_p3_doorPosition(instance, &context_Interaction_Context_Interaction->p3_doorPosition);
    Cse_Read_p7_responseComputed(instance, &context_Interaction_Context_Interaction->p7_responseComputed);

    /* handle external event(s) */
    context_Interaction_Context_Interaction->EVENT = CONTEXT_INTERACTION_EVENT_T_NO_EVENT;
    {
        /* @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa */
        SignalEvent_execution_completed_type signalEvent_execution_completed;
        Cse_Read_p3_execution_completed(instance, &signalEvent_execution_completed);
        if(signalEvent_execution_completed.trigger == TRUE) {
            context_Interaction_Context_Interaction->EVENT = CONTEXT_INTERACTION_EVENT_T_execution_completed;
        }
    }
    if(context_Interaction_Context_Interaction->EVENT == CONTEXT_INTERACTION_EVENT_T_NO_EVENT) {
        /* @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa */
        SignalEvent_execution_completed_type signalEvent_execution_completed;
        Cse_Read_p7_execution_completed(instance, &signalEvent_execution_completed);
        if(signalEvent_execution_completed.trigger == TRUE) {
            context_Interaction_Context_Interaction->EVENT = CONTEXT_INTERACTION_EVENT_T_execution_completed;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    context_Interaction_Context_Interaction->WALL_CLOCK = tal_GetTime();
    context_Interaction_Context_Interaction->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal.WALL_CLOCK \
        = tal_GetTime();
    context_Interaction_Context_Interaction->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal.WALL_CLOCK \
        = tal_GetTime();

    /* Copy data in */
    pContext_Interaction->response_current = context_Interaction_Context_Interaction->p7_responseComputed;
    pContext_Interaction->position_current = context_Interaction_Context_Interaction->p3_doorPosition;

    (void)basic_Context_Interaction(context_Interaction_Context_Interaction);

    /* Copy data out */
    context_Interaction_Context_Interaction->p1_modeSelected = pContext_Interaction->mode_requested;
    context_Interaction_Context_Interaction->p2_doorPosition = pContext_Interaction->position_requested;

    /* write output(s) */
    Cse_Write_p1_modeSelected(instance, &context_Interaction_Context_Interaction->p1_modeSelected);
    Cse_Write_p2_doorPosition(instance, &context_Interaction_Context_Interaction->p2_doorPosition);

    /* trigger event(s) */
    if (context_Interaction_Context_Interaction->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal.EVENT \
        == CONTEXT_INTERACTION_MODE_CHANGE_SIGNAL_EVENT_T_mode_change_signal) {
        context_Interaction_Context_Interaction->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal.EVENT \
            = CONTEXT_INTERACTION_MODE_CHANGE_SIGNAL_EVENT_T_NO_EVENT;
        Cse_Trigger_p1_mode_change_signal(instance);
    }
    if (context_Interaction_Context_Interaction->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal.EVENT \
        == CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_door_status_change_signal) {
        context_Interaction_Context_Interaction->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal.EVENT \
            = CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_NO_EVENT;
        Cse_Trigger_p2_door_status_change_signal(instance);
    }
}

/**********************************************************************************
 * Exit function invoked at execution ending
 **********************************************************************************/
void Context_Interaction_Context_Interaction_end(Cse_Context_Interaction_Struct* instance) {
    /* Get component Context Interaction from "parent" */
    Context_Interaction *pContext_Interaction = instance->parent;

    /* Get behavior context_Interaction_Context_Interaction from the Context Interaction */
    Context_Interaction_struct *context_Interaction_Context_Interaction = &pContext_Interaction->Context_Interaction_Context_Interaction;

    basic_Context_Interaction_end(context_Interaction_Context_Interaction);
}

/* end of file */
