/* @date 2026-07-01T10:15:55.211903400Z */

/**********************************************************************************
 * @file Context_Interaction.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 **********************************************************************************/

#ifndef CONTEXT_INTERACTION_H
#define CONTEXT_INTERACTION_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stdio.h>
#include "Tal.h"
#include <stdlib.h>
#include "Context_Interaction_itf.h"
#include "internal_types.h"
#include "Context_Interaction_Context_Interaction.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Context_Interaction_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 */
typedef struct {
} Context_Interaction_VTable;

/** @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95 */
typedef struct Context_Interaction_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Context_Interaction_*);

	/** Pointer to virtual table */
	const Context_Interaction_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Integer:mode_requested
	 * @generated_from c27cf313-12d7-41c5-abaa-2c91af71f068
	 */
	Integer mode_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_requested
	 * @generated_from 7323f884-f600-4cc5-9140-772a05607c61
	 */
	Integer position_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:response_current
	 * @generated_from b5f2433c-95eb-463e-9ca0-d39b4d2457e5
	 */
	Integer response_current;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_current
	 * @generated_from 17b84b62-44a6-40d1-9e54-90d9d76cb5c1
	 */
	Integer position_current;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:action_requested
	 * @generated_from 440c9c7c-3755-4167-8f32-40dd74b0ed84
	 */
	Integer action_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:action_requested
	 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
	 * @reverse_ignore
	 */
	Context_Interaction_struct Context_Interaction_Context_Interaction;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Public attribute for composition relation to Integer:action_requested
	 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
	 * @reverse_ignore
	 */
	Cse_Context_Interaction_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Context_Interaction;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 */
void Context_Interaction_ctor(Context_Interaction* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef CONTEXT_INTERACTION_H */

/* end of file */