/* @date 2026-07-01T10:15:55.119501600Z */

/**********************************************************************************
 * @file Context_Interaction_Context_Interaction_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "Context_Interaction_Context_Interaction.h"
#include "Context_Interaction.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                 instance->p1_modeSelected
#define p1                                              p1_modeSelected
#define p2_doorPosition                                 instance->p2_doorPosition
#define p2                                              p2_doorPosition
#define p3_doorPosition                                 instance->p3_doorPosition
#define p3                                              p3_doorPosition
#define p7_responseComputed                             instance->p7_responseComputed
#define p7                                              p7_responseComputed
#define mode_requested                                  instance->classifier->mode_requested
#define position_requested                              instance->classifier->position_requested
#define response_current                                instance->classifier->response_current
#define position_current                                instance->classifier->position_current
#define action_requested                                instance->classifier->action_requested

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Close_Entry_1(...)                          Context_Interaction_Close_Entry_1(__VA_ARGS__)
#define GO_Entry_1(...)                             Context_Interaction_GO_Entry_1(__VA_ARGS__)
#define Open_Entry_1(...)                           Context_Interaction_Open_Entry_1(__VA_ARGS__)
#define door_status_change_Entry_1(...)             Context_Interaction_door_status_change_Entry_1(__VA_ARGS__)
#define idle_Entry_1(...)                           Context_Interaction_idle_Entry_1(__VA_ARGS__)
#define maint_Entry_1(...)                          Context_Interaction_maint_Entry_1(__VA_ARGS__)
#define mode_change_Entry_1(...)                    Context_Interaction_mode_change_Entry_1(__VA_ARGS__)

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Function Close_Entry
 * Implements "Entry" of State: Close
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e1b913da-e022-41cc-956e-057612b93655
 * @generated_from b46fcf6e-48e2-4f98-8cfe-a70a2228a72d
 **********************************************************************************/
void Close_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entryb46fcf6e-48e2-4f98-8cfe-a70a2228a72d) do not remove */


    /* END_USER_CODE(Entryb46fcf6e-48e2-4f98-8cfe-a70a2228a72d) do not remove */
    position_requested=0;
}

/**********************************************************************************
 * Function GO_Entry
 * Implements "Entry" of State: GO
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 1c1ea3f0-eaad-40f7-9352-50a54f20d2b7
 * @generated_from 82a00b74-7f3c-4181-a148-5dcb08d66a29
 **********************************************************************************/
void GO_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entry82a00b74-7f3c-4181-a148-5dcb08d66a29) do not remove */


    /* END_USER_CODE(Entry82a00b74-7f3c-4181-a148-5dcb08d66a29) do not remove */
    mode_requested=0;
}

/**********************************************************************************
 * Function Open_Entry
 * Implements "Entry" of State: Open
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 01aeb3b6-59ca-48f1-89ce-f6a52d3f8206
 * @generated_from cc28478c-6591-4bd9-b30a-a4f0d4d63c7c
 **********************************************************************************/
void Open_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entrycc28478c-6591-4bd9-b30a-a4f0d4d63c7c) do not remove */


    /* END_USER_CODE(Entrycc28478c-6591-4bd9-b30a-a4f0d4d63c7c) do not remove */
    position_requested=1;
}

/**********************************************************************************
 * Function door_status_change_Entry
 * Implements "Entry" of State: door status change
 * Entry calls Activity: door status change signal
 *
 * @generated_from 94ded1b0-ba11-4616-aa3d-7f016ca0d728
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
void door_status_change_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entry8bccc404-b618-411c-8877-eb3d8c945c58) do not remove */


    /* END_USER_CODE(Entry8bccc404-b618-411c-8877-eb3d8c945c58) do not remove */
    instance->DONE_ACTIVITY = basic_Context_Interaction_door_status_change_signal(&(instance->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal));
}

/**********************************************************************************
 * Function idle_Entry
 * Implements "Entry" of State: idle
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from e6e54d5c-74f2-4f73-9b55-0b17a61e32c8
 * @generated_from cf23e36b-943e-431d-b64d-4f8a2c2a9768
 **********************************************************************************/
void idle_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entrycf23e36b-943e-431d-b64d-4f8a2c2a9768) do not remove */


    /* END_USER_CODE(Entrycf23e36b-943e-431d-b64d-4f8a2c2a9768) do not remove */
    char input[100];
    char response[100];

    // retrieve info about current response
    if (response_current == 0)
    {
        strcpy(response, "CLOSED");
        tal_printf("Current Door status: %s\n", response);
        tal_printf("Select mode (o/m): ");

        if (fgets(input, sizeof(input), stdin) != NULL)
        {
            // Remove newline
            input[strcspn(input, "\n")] = '\0';
        }

        if (strcmp(input, "o") == 0 || strcmp(input, "O") == 0)
        {
            action_requested = 1;
        }
        else if (strcmp(input, "m") == 0 || strcmp(input, "M") == 0)
        {
            action_requested = 2;
        }

    }
    else if (response_current == 1)
    {
        strcpy(response, "OPEN");

        tal_printf("Current Door status: %s\n", response);
        tal_printf("Select mode (c/m): ");

        if (fgets(input, sizeof(input), stdin) != NULL)
        {
            // Remove newline
            input[strcspn(input, "\n")] = '\0';
        }

        if (strcmp(input, "c") == 0 || strcmp(input, "C") == 0)
        {
            action_requested = 0;
        }
        else if (strcmp(input, "m") == 0 || strcmp(input, "M") == 0)
        {
            action_requested = 2;
        }
    }
    else if (response_current == 2)
    {
        if (position_current != position_requested)
        {

            if (position_requested == 1)
            {
                tal_printf("The door is in maintenance, it was not possible to set the status to OPEN\n");
            }
            else if (position_requested == 0)
            {
                tal_printf("The door is in maintenance, it was not possible to set the status to CLOSED\n");
            }
        }

        strcpy(response, "MAINT");

        tal_printf("Current Door status: %s\n", response);
        tal_printf("Select mode (c/o/g): ");

        if (fgets(input, sizeof(input), stdin) != NULL)
        {
            // Remove newline
            input[strcspn(input, "\n")] = '\0';
        }

        if (strcmp(input, "c") == 0 || strcmp(input, "C") == 0)
        {
            action_requested = 0;
        }
        if (strcmp(input, "o") == 0 || strcmp(input, "O") == 0)
        {
            action_requested = 1;
        }
        else if (strcmp(input, "g") == 0 || strcmp(input, "G") == 0)
        {
            action_requested = 3;
        }
    }
    else if (response_current == 3)
    {
        strcpy(response, "OBSTRUCTED");

        tal_printf("Current Door status: %s\n", response);
        tal_printf("Select mode (c/o): ");

        if (fgets(input, sizeof(input), stdin) != NULL)
        {
            // Remove newline
            input[strcspn(input, "\n")] = '\0';
        }

        if (strcmp(input, "c") == 0 || strcmp(input, "C") == 0)
        {
            action_requested = 0;
        }
        if (strcmp(input, "o") == 0 || strcmp(input, "O") == 0)
        {
            action_requested = 1;
        }
    }
    ;
}

/**********************************************************************************
 * Function maint_Entry
 * Implements "Entry" of State: maint
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 534195b5-15dd-4955-bae1-6dccb26f9d77
 * @generated_from e573cf0c-e673-413a-b727-9d5011bef19e
 **********************************************************************************/
void maint_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entrye573cf0c-e673-413a-b727-9d5011bef19e) do not remove */


    /* END_USER_CODE(Entrye573cf0c-e673-413a-b727-9d5011bef19e) do not remove */
    mode_requested=1;
}

/**********************************************************************************
 * Function mode_change_Entry
 * Implements "Entry" of State: mode change
 * Entry calls Activity: mode change signal
 *
 * @generated_from 460408d9-eb18-4f88-ab8b-17dfc320f0a7
 * @generated_from ecd03eac-9979-4c36-bc22-ea38b76a2ea8
 **********************************************************************************/
void mode_change_Entry_1(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(Entryecd03eac-9979-4c36-bc22-ea38b76a2ea8) do not remove */


    /* END_USER_CODE(Entryecd03eac-9979-4c36-bc22-ea38b76a2ea8) do not remove */
    instance->DONE_ACTIVITY = basic_Context_Interaction_mode_change_signal(&(instance->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal));
}

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void Context_Interaction_user_init(Context_Interaction_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance;

    /* END_USER_CODE(init_state_machine) do not remove */
}

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void Context_Interaction_user_end(Context_Interaction_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */

    /* END_USER_CODE(end_state_machine) do not remove */
    basic_Context_Interaction_door_status_change_signal_end(&(instance->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal));
    basic_Context_Interaction_mode_change_signal_end(&(instance->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal));
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

/* end of file */
