/* @date 2026-07-01T10:15:55.220933700Z */

/**********************************************************************************
 * @file Context_Interaction.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Context_Interaction.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 */
static void Context_Interaction_dtor(struct Context_Interaction_* self);

/** vtable variable declaration */
static const Context_Interaction_VTable vtable_Context_Interaction = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 */
void Context_Interaction_ctor(Context_Interaction* self) {
	/** Init pointer to destructor */
	self->dtor = &Context_Interaction_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Context_Interaction;

	/** Default values */
	self->mode_requested = 0;
	self->position_requested = 0;
	self->response_current = 0;
	self->position_current = 0;
	self->action_requested = 0;

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
	Context_Interaction_struct_ctor(&self->Context_Interaction_Context_Interaction, self);
}

/**
 * Destructor generated automatically
 * @generated_from f0af1632-97f5-42ac-98bf-fa2ebd53cd95
 * @reverse_ignore
 */
static void Context_Interaction_dtor(struct Context_Interaction_* self) {
	/** Call hierarchical destructors */
	self->Context_Interaction_Context_Interaction.dtor(&self->Context_Interaction_Context_Interaction);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */