/* @date 2026-07-01T10:15:55.081928400Z */

/**********************************************************************************
 * @file Context_Interaction_Context_Interaction.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 * @reverse_ignore
 **********************************************************************************/

/* Application code for statemachine "Context Interaction" */

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "Context_Interaction_Context_Interaction.h"
#include "Context_Interaction.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                 instance->p1_modeSelected
#define p1                                              p1_modeSelected
#define p2_doorPosition                                 instance->p2_doorPosition
#define p2                                              p2_doorPosition
#define p3_doorPosition                                 instance->p3_doorPosition
#define p3                                              p3_doorPosition
#define p7_responseComputed                             instance->p7_responseComputed
#define p7                                              p7_responseComputed
#define mode_requested                                  instance->classifier->mode_requested
#define position_requested                              instance->classifier->position_requested
#define response_current                                instance->classifier->response_current
#define position_current                                instance->classifier->position_current
#define action_requested                                instance->classifier->action_requested

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Close_Entry_1(...)                          Context_Interaction_Close_Entry_1(__VA_ARGS__)
#define GO_Entry_1(...)                             Context_Interaction_GO_Entry_1(__VA_ARGS__)
#define Open_Entry_1(...)                           Context_Interaction_Open_Entry_1(__VA_ARGS__)
#define door_status_change_Entry_1(...)             Context_Interaction_door_status_change_Entry_1(__VA_ARGS__)
#define idle_Entry_1(...)                           Context_Interaction_idle_Entry_1(__VA_ARGS__)
#define maint_Entry_1(...)                          Context_Interaction_maint_Entry_1(__VA_ARGS__)
#define mode_change_Entry_1(...)                    Context_Interaction_mode_change_Entry_1(__VA_ARGS__)

/**********************************************************************************
 * Function Context_Interaction_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
static void Context_Interaction_struct_dtor(struct Context_Interaction_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function Context_Interaction_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void Context_Interaction_struct_ctor(struct Context_Interaction_struct * const self, struct Context_Interaction_* classifier) \
    {
    /* Init pointer to destructor */
    self->dtor = &Context_Interaction_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Call hierarchical constructors */
    Context_Interaction_door_status_change_signal_struct_ctor(&self->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal, \
        classifier);
    Context_Interaction_mode_change_signal_struct_ctor(&self->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal, \
        classifier);
}
/**********************************************************************************
 * Function basic_Context_Interaction_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction_init(Context_Interaction_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T_Context_Interaction)0;
    instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_VOID;

    basic_Context_Interaction_door_status_change_signal_init(&(instance->door_status_change_Entry_1_Context_Interaction_Context_Interaction_door_status_change_signal));

    basic_Context_Interaction_mode_change_signal_init(&(instance->mode_change_Entry_1_Context_Interaction_Context_Interaction_mode_change_signal));

    Context_Interaction_user_init(instance);
}

/**********************************************************************************
 * Function basic_Context_Interaction
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction(Context_Interaction_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> idle */
        /* @generated_from 9a9caecd-ad03-48a3-bb30-740b5ce84501 */
        idle_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_idle */
        instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_idle;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State maint */
        /* @generated_from 534195b5-15dd-4955-bae1-6dccb26f9d77 */
        case CONTEXT_INTERACTION_STATE_T_maint: {
            /* Transition maint -> mode change */
            /* @generated_from e745adb7-0772-4847-8a00-5f945d4c5305 */
            mode_change_Entry_1(instance); /* Entry mode change signal */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_mode_change;
            break; /* end of CONTEXT_INTERACTION_STATE_T_maint */
        }
        /* State mode change */
        /* @generated_from 460408d9-eb18-4f88-ab8b-17dfc320f0a7 */
        case CONTEXT_INTERACTION_STATE_T_mode_change: {
            /* Transition mode change -> request sent */
            /* @generated_from e319c437-90da-4fbb-afd8-ae87e8109708 */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_request_sent;
            break; /* end of CONTEXT_INTERACTION_STATE_T_mode_change */
        }
        /* State idle */
        /* @generated_from e6e54d5c-74f2-4f73-9b55-0b17a61e32c8 */
        case CONTEXT_INTERACTION_STATE_T_idle: {
            if( action_requested==0 ) {
                /* Transition idle -> Close */
                /* @generated_from 37a887b1-7076-465c-923a-5bfeda739b28 */
                Close_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_Close */
                instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_Close;
            } else if( action_requested==2 ) {
                /* Transition idle -> maint */
                /* @generated_from 72d8a974-b23d-4b2f-8d5a-a0cbf53a8b7f */
                maint_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_maint */
                instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_maint;
            } else if( action_requested==3 ) {
                /* Transition idle -> GO */
                /* @generated_from ee51e2e8-2486-4b38-8001-5195860cc5d2 */
                GO_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_GO */
                instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_GO;
            } else if( action_requested==1 ) {
                /* Transition idle -> Open */
                /* @generated_from f183d229-2904-49d5-aa8b-38f70696438d */
                Open_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_Open */
                instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_Open;
            } else {
                /* stay in th state */;
            }
            break; /* end of CONTEXT_INTERACTION_STATE_T_idle */
        }
        /* State GO */
        /* @generated_from 1c1ea3f0-eaad-40f7-9352-50a54f20d2b7 */
        case CONTEXT_INTERACTION_STATE_T_GO: {
            /* Transition GO -> mode change */
            /* @generated_from 73f82ddb-cd4b-4532-868f-59dee36e24a7 */
            mode_change_Entry_1(instance); /* Entry mode change signal */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_mode_change;
            break; /* end of CONTEXT_INTERACTION_STATE_T_GO */
        }
        /* State Open */
        /* @generated_from 01aeb3b6-59ca-48f1-89ce-f6a52d3f8206 */
        case CONTEXT_INTERACTION_STATE_T_Open: {
            /* Transition Open -> door status change */
            /* @generated_from f002f6e6-0506-4089-8154-447432ffb7e4 */
            door_status_change_Entry_1(instance); /* Entry door status change signal */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_door_status_change;
            break; /* end of CONTEXT_INTERACTION_STATE_T_Open */
        }
        /* State Close */
        /* @generated_from e1b913da-e022-41cc-956e-057612b93655 */
        case CONTEXT_INTERACTION_STATE_T_Close: {
            /* Transition Close -> door status change */
            /* @generated_from 80013cc2-b379-4320-a8d4-95a6fc820c9a */
            door_status_change_Entry_1(instance); /* Entry door status change signal */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_door_status_change;
            break; /* end of CONTEXT_INTERACTION_STATE_T_Close */
        }
        /* State request sent */
        /* @generated_from 205bd8d4-1720-43cc-8cd3-262bea545ced */
        case CONTEXT_INTERACTION_STATE_T_request_sent: {
            if( instance->EVENT == CONTEXT_INTERACTION_EVENT_T_execution_completed ) {
                /* Transition request sent -> idle */
                /* @generated_from 9b601dce-e9e7-4cd8-aab4-a5209f2ae279 */
                /* @generated_from b81b57ad-b54f-466a-b17f-8b3d246395e2 */
                idle_Entry_1(instance); /* Entry of CONTEXT_INTERACTION_STATE_T_idle */
                instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_idle;
                instance->EVENT = CONTEXT_INTERACTION_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of CONTEXT_INTERACTION_STATE_T_request_sent */
        }
        /* State door status change */
        /* @generated_from 94ded1b0-ba11-4616-aa3d-7f016ca0d728 */
        case CONTEXT_INTERACTION_STATE_T_door_status_change: {
            /* Transition door status change -> request sent */
            /* @generated_from d9d29e3d-672e-42d0-a0de-4c5b63224eb5 */
            instance->CURRENT_STATE_0 = CONTEXT_INTERACTION_STATE_T_request_sent;
            break; /* end of CONTEXT_INTERACTION_STATE_T_door_status_change */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************************
 * Function basic_Context_Interaction_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 5cbe33b4-eaab-4cf1-b3ee-20ca7fe942de
 **********************************************************************************/
void basic_Context_Interaction_end(Context_Interaction_struct *instance) {
    Context_Interaction_user_end(instance);
}

/* end of file */
