/* @date 2026-07-01T10:15:55.139557500Z */

/**********************************************************************************
 * @file Context_Interaction_Context_Interaction_door_status_change_signal.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "door status change signal" */

#include "Context_Interaction_Context_Interaction_door_status_change_signal.h"

#include "Context_Interaction.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                     instance->p1_modeSelected
#define p1                                                  p1_modeSelected
#define p2_doorPosition                                     instance->p2_doorPosition
#define p2                                                  p2_doorPosition
#define p3_doorPosition                                     instance->p3_doorPosition
#define p3                                                  p3_doorPosition
#define p7_responseComputed                                 instance->p7_responseComputed
#define p7                                                  p7_responseComputed
#define mode_requested                                      instance->classifier->mode_requested
#define position_requested                                  instance->classifier->position_requested
#define response_current                                    instance->classifier->response_current
#define position_current                                    instance->classifier->position_current
#define action_requested                                    instance->classifier->action_requested

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T default_peekEvent_Context_Interaction_Context_Interaction_door_status_change_signal(const \
    Context_Interaction_door_status_change_signal_struct * const instance) {
    return instance->EVENT;
}
static CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T default_nextEvent_Context_Interaction_Context_Interaction_door_status_change_signal(Context_Interaction_door_status_change_signal_struct \
    *instance) {
    (void)instance;
    return CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_Context_Interaction_Context_Interaction_door_status_change_signal(Context_Interaction_door_status_change_signal_struct \
    *instance, CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_Context_Interaction_Context_Interaction_door_status_change_signal(const Context_Interaction_door_status_change_signal_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function Context_Interaction_door_status_change_signal_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
static void Context_Interaction_door_status_change_signal_struct_dtor(struct Context_Interaction_door_status_change_signal_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function Context_Interaction_door_status_change_signal_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
void Context_Interaction_door_status_change_signal_struct_ctor(struct Context_Interaction_door_status_change_signal_struct_ \
    * const self, struct Context_Interaction_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &Context_Interaction_door_status_change_signal_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_Context_Interaction_Context_Interaction_door_status_change_signal;
    self->nextEVENT = &default_nextEvent_Context_Interaction_Context_Interaction_door_status_change_signal;
    self->sendEVENT = &default_sendEvent_Context_Interaction_Context_Interaction_door_status_change_signal;
}
/**********************************************************************************
 * Function basic_Context_Interaction_door_status_change_signal_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
void basic_Context_Interaction_door_status_change_signal_init(Context_Interaction_door_status_change_signal_struct *instance) \
    {
    instance->EVENT = CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_Context_Interaction_door_status_change_signal)0;

}

/**********************************************************************************
 * Function basic_Context_Interaction_door_status_change_signal
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
Boolean basic_Context_Interaction_door_status_change_signal(Context_Interaction_door_status_change_signal_struct *instance) \
    {
    /* initialization */
    if(isRunning_Context_Interaction_Context_Interaction_door_status_change_signal(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node SendSignalAction */
    /* @generated_from 5f4dd48d-b875-4d47-9b61-4cb32c53f3e7 */
    /* @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89 */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-InitialNode */
        Boolean success = instance->sendEVENT(instance, CONTEXT_INTERACTION_DOOR_STATUS_CHANGE_SIGNAL_EVENT_T_door_status_change_signal);
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from e048a036-a1b6-4a16-8d49-f0d18fce9f2d */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-SendSignalAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_Context_Interaction_Context_Interaction_door_status_change_signal(instance)) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function basic_Context_Interaction_door_status_change_signal_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 8bccc404-b618-411c-8877-eb3d8c945c58
 **********************************************************************************/
void basic_Context_Interaction_door_status_change_signal_end(Context_Interaction_door_status_change_signal_struct *instance) \
    {
    (void)instance;
}

/* end of file */
