/* @date 2026-07-01T10:15:54.758716900Z */

/**********************************************************************************
 * 
 * @file Cse.c
 * 
 * Automatically generated by Software Production Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Tal.h" /* tal_allocate */
#include "Cse_cfg.h"
#include "Cse_hook.h"
#define CSE_C /* Macro to include only some specific parts of include files */

#include "Train_Door_System.h" /* Train Door System class definition */
#include <string.h> /* memset for memory init */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/
Train_Door_System* pTrain_Door_System;

task_descriptor task_descriptors[NUMBER_OF_TASKS];

/**********************************************************************************
 * Functions Implementation 
 **********************************************************************************/

/**
 * Function to Trigger door status change signal on p1 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_Train_Door_System_context_Interaction_p1_door_status_change_signal(void) {
	SignalEvent_door_status_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p1_door_status_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Return(&trigger);
}

/**
 * Function to Trigger mode change signal on p1 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_Train_Door_System_context_Interaction_p1_mode_change_signal(void) {
	SignalEvent_mode_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p1_mode_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Return(&trigger);
}

/**
 * Function to Trigger door status change signal on p2 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_Train_Door_System_context_Interaction_p2_door_status_change_signal(void) {
	SignalEvent_door_status_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p2_door_status_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Return(&trigger);
}

/**
 * Function to Trigger mode change signal on p2 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_Train_Door_System_context_Interaction_p2_mode_change_signal(void) {
	SignalEvent_mode_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p2_mode_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Return(&trigger);
}

/**
 * Function to Trigger execution completed on p2 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_Train_Door_System_context_Interaction_p2_execution_completed(void) {
	SignalEvent_execution_completed_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p2_execution_completed)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Return(&trigger);
}

/**
 * Function to Trigger door status change signal on p3 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_door_status_change_signal(void) {
	SignalEvent_door_status_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_context_Interaction_p3_door_status_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Return(&trigger);
}

/**
 * Function to Trigger mode change signal on p3 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_mode_change_signal(void) {
	SignalEvent_mode_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_context_Interaction_p3_mode_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Return(&trigger);
}

/**
 * Function to Trigger execution completed on p3 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_execution_completed(void) {
	SignalEvent_execution_completed_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_context_Interaction_p3_execution_completed)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Return(&trigger);
}

/**
 * Function to Trigger door status change signal on p5 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_door_status_change_signal(void) {
	SignalEvent_door_status_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_p5_door_status_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Return(&trigger);
}

/**
 * Function to Trigger mode change signal on p5 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_mode_change_signal(void) {
	SignalEvent_mode_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_p5_mode_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Return(&trigger);
}

/**
 * Function to Trigger execution completed on p5 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_execution_completed(void) {
	SignalEvent_execution_completed_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_p5_execution_completed)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Return(&trigger);
}

/**
 * Function to Trigger execution completed on p7 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_Train_Door_System_train_Door_Controller_p7_execution_completed(void) {
	SignalEvent_execution_completed_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_context_Interaction_p7_execution_completed)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Return(&trigger);
}

/**
 * Function to Trigger door status change signal on p1 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_Train_Door_System_proximity_Sensor_p1_door_status_change_signal(void) {
	SignalEvent_door_status_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p11_door_status_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Return(&trigger);
}

/**
 * Function to Trigger mode change signal on p1 port
 * Function is not static because it can be invoked from test infrastructure
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_Train_Door_System_proximity_Sensor_p1_mode_change_signal(void) {
	SignalEvent_mode_change_signal_type trigger;
	trigger.trigger = (trigger_type)1;
	
	Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Start(&trigger);
	for (uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++) {
		((char*) &pTrain_Door_System->to_train_Door_Controller_p11_mode_change_signal)[byteIdx] = ((char*) &trigger)[byteIdx];
	}
	Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Return(&trigger);
}

/**
 * Function to send modeSelected on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
static void Cse_Write_Train_Door_System_context_Interaction_p1_modeSelected(Integer* data){
	Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_context_Interaction_p1_modeSelected)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Return(data);
}

/**
 * Function to send doorPosition on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Write_Train_Door_System_context_Interaction_p2_doorPosition(Integer* data){
	Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_context_Interaction_p2_doorPosition)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Return(data);
}

/**
 * Function to send doorPosition on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Write_Train_Door_System_train_Door_Controller_p3_doorPosition(Integer* data){
	Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_train_Door_Controller_p3_doorPosition)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Return(data);
}

/**
 * Function to send doorPosition on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Write_Train_Door_System_train_Door_Controller_p5_doorPosition(Integer* data){
	Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_train_Door_Controller_p5_doorPosition)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Return(data);
}

/**
 * Function to send responseComputed on p7 port
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
static void Cse_Write_Train_Door_System_train_Door_Controller_p7_responseComputed(Integer* data){
	Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_train_Door_Controller_p7_responseComputed)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Return(data);
}

/**
 * Function to send obstructionDetected on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
static void Cse_Write_Train_Door_System_proximity_Sensor_p1_obstructionDetected(Integer* data){
	Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Start(data);

	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &pTrain_Door_System->from_proximity_Sensor_p1_obstructionDetected)[byteIdx] = ((char*) data)[byteIdx];
	}

	Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Return(data);
}

/**
 * Function to read door status change signal on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
static void Cse_Read_Train_Door_System_context_Interaction_p3_door_status_change_signal(SignalEvent_door_status_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_context_Interaction_p3_door_status_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_context_Interaction_p3_door_status_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Return(data);
	// }
}

/**
 * Function to read mode change signal on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
static void Cse_Read_Train_Door_System_context_Interaction_p3_mode_change_signal(SignalEvent_mode_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_context_Interaction_p3_mode_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_context_Interaction_p3_mode_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Return(data);
	// }
}

/**
 * Function to read execution completed on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
static void Cse_Read_Train_Door_System_context_Interaction_p3_execution_completed(SignalEvent_execution_completed_type* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_context_Interaction_p3_execution_completed)[byteIdx];
	}

	pTrain_Door_System->to_context_Interaction_p3_execution_completed.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Return(data);
	// }
}

/**
 * Function to read execution completed on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
static void Cse_Read_Train_Door_System_context_Interaction_p7_execution_completed(SignalEvent_execution_completed_type* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_context_Interaction_p7_execution_completed)[byteIdx];
	}

	pTrain_Door_System->to_context_Interaction_p7_execution_completed.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Return(data);
	// }
}

/**
 * Function to read door status change signal on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p1_door_status_change_signal(SignalEvent_door_status_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p1_door_status_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p1_door_status_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Return(data);
	// }
}

/**
 * Function to read mode change signal on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p1_mode_change_signal(SignalEvent_mode_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p1_mode_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p1_mode_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Return(data);
	// }
}

/**
 * Function to read door status change signal on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p2_door_status_change_signal(SignalEvent_door_status_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p2_door_status_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p2_door_status_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Return(data);
	// }
}

/**
 * Function to read mode change signal on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p2_mode_change_signal(SignalEvent_mode_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p2_mode_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p2_mode_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Return(data);
	// }
}

/**
 * Function to read execution completed on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p2_execution_completed(SignalEvent_execution_completed_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p2_execution_completed)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p2_execution_completed.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Return(data);
	// }
}

/**
 * Function to read door status change signal on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p11_door_status_change_signal(SignalEvent_door_status_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p11_door_status_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p11_door_status_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Return(data);
	// }
}

/**
 * Function to read mode change signal on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p11_mode_change_signal(SignalEvent_mode_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_Controller_p11_mode_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_Controller_p11_mode_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Return(data);
	// }
}

/**
 * Function to read door status change signal on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
static void Cse_Read_Train_Door_System_train_Door_p5_door_status_change_signal(SignalEvent_door_status_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_door_status_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_p5_door_status_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_p5_door_status_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Return(data);
	// }
}

/**
 * Function to read mode change signal on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
static void Cse_Read_Train_Door_System_train_Door_p5_mode_change_signal(SignalEvent_mode_change_signal_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_mode_change_signal_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_p5_mode_change_signal)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_p5_mode_change_signal.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Return(data);
	// }
}

/**
 * Function to read execution completed on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
static void Cse_Read_Train_Door_System_train_Door_p5_execution_completed(SignalEvent_execution_completed_type* data){
	Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(SignalEvent_execution_completed_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->to_train_Door_p5_execution_completed)[byteIdx];
	}

	pTrain_Door_System->to_train_Door_p5_execution_completed.trigger = false;
	// if(data->trigger == true){
		Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Return(data);
	// }
}

/**
 * Function to read doorPosition on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Read_Train_Door_System_context_Interaction_p3_doorPosition(Integer* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_train_Door_Controller_p3_doorPosition)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Return(data);
}

/**
 * Function to read responseComputed on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
static void Cse_Read_Train_Door_System_context_Interaction_p7_responseComputed(Integer* data){
	Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_train_Door_Controller_p7_responseComputed)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Return(data);
}

/**
 * Function to read modeSelected on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p1_modeSelected(Integer* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_context_Interaction_p1_modeSelected)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Return(data);
}

/**
 * Function to read doorPosition on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p2_doorPosition(Integer* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_context_Interaction_p2_doorPosition)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Return(data);
}

/**
 * Function to read obstructionDetected on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
static void Cse_Read_Train_Door_System_train_Door_Controller_p11_obstructionDetected(Integer* data){
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_proximity_Sensor_p1_obstructionDetected)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Return(data);
}

/**
 * Function to read doorPosition on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
static void Cse_Read_Train_Door_System_train_Door_p5_doorPosition(Integer* data){
	Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Start(data);
	for(uint16_t byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &pTrain_Door_System->from_train_Door_Controller_p5_doorPosition)[byteIdx];
	}
	Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Return(data);
}

/**
 * Function mapping the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 */
void Cse_component_instances_init(void) { 
	pTrain_Door_System = tal_allocate(sizeof(Train_Door_System)); /* Allocate variable (option: objects_allocation:Dynamic) */
	memset(pTrain_Door_System, 0, sizeof(Train_Door_System)); /* Erase memory section for Behaviors proper implementation */ 
	Train_Door_System_ctor(pTrain_Door_System); /* Call the constructor to intialize relations */
	
	/* BEG: Context_Interaction Communication Interface Configuration */
	/* Write functions */
	pTrain_Door_System->context_Interaction.cse_itf.Write_p1_modeSelected = &Cse_Write_Train_Door_System_context_Interaction_p1_modeSelected;
	pTrain_Door_System->context_Interaction.cse_itf.Write_p2_doorPosition = &Cse_Write_Train_Door_System_context_Interaction_p2_doorPosition;
	/* Trigger functions */
	pTrain_Door_System->context_Interaction.cse_itf.Trigger_p1_door_status_change_signal = &Cse_Trigger_Train_Door_System_context_Interaction_p1_door_status_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Trigger_p1_mode_change_signal = &Cse_Trigger_Train_Door_System_context_Interaction_p1_mode_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Trigger_p2_door_status_change_signal = &Cse_Trigger_Train_Door_System_context_Interaction_p2_door_status_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Trigger_p2_mode_change_signal = &Cse_Trigger_Train_Door_System_context_Interaction_p2_mode_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Trigger_p2_execution_completed = &Cse_Trigger_Train_Door_System_context_Interaction_p2_execution_completed;
	/* Read functions */
	pTrain_Door_System->context_Interaction.cse_itf.Read_p3_doorPosition = &Cse_Read_Train_Door_System_context_Interaction_p3_doorPosition;
	pTrain_Door_System->context_Interaction.cse_itf.Read_p7_responseComputed = &Cse_Read_Train_Door_System_context_Interaction_p7_responseComputed;
	pTrain_Door_System->context_Interaction.cse_itf.Read_p3_door_status_change_signal = &Cse_Read_Train_Door_System_context_Interaction_p3_door_status_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Read_p3_mode_change_signal = &Cse_Read_Train_Door_System_context_Interaction_p3_mode_change_signal;
	pTrain_Door_System->context_Interaction.cse_itf.Read_p3_execution_completed = &Cse_Read_Train_Door_System_context_Interaction_p3_execution_completed;
	pTrain_Door_System->context_Interaction.cse_itf.Read_p7_execution_completed = &Cse_Read_Train_Door_System_context_Interaction_p7_execution_completed;
	/* Server call functions */
	/* END: Context_Interaction Cmmunication Interface Configuration */

	/* BEG: Train_Door_Controller Communication Interface Configuration */
	/* Write functions */
	pTrain_Door_System->train_Door_Controller.cse_itf.Write_p3_doorPosition = &Cse_Write_Train_Door_System_train_Door_Controller_p3_doorPosition;
	pTrain_Door_System->train_Door_Controller.cse_itf.Write_p5_doorPosition = &Cse_Write_Train_Door_System_train_Door_Controller_p5_doorPosition;
	pTrain_Door_System->train_Door_Controller.cse_itf.Write_p7_responseComputed = &Cse_Write_Train_Door_System_train_Door_Controller_p7_responseComputed;
	/* Trigger functions */
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p3_door_status_change_signal = &Cse_Trigger_Train_Door_System_train_Door_Controller_p3_door_status_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p3_mode_change_signal = &Cse_Trigger_Train_Door_System_train_Door_Controller_p3_mode_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p3_execution_completed = &Cse_Trigger_Train_Door_System_train_Door_Controller_p3_execution_completed;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p5_door_status_change_signal = &Cse_Trigger_Train_Door_System_train_Door_Controller_p5_door_status_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p5_mode_change_signal = &Cse_Trigger_Train_Door_System_train_Door_Controller_p5_mode_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p5_execution_completed = &Cse_Trigger_Train_Door_System_train_Door_Controller_p5_execution_completed;
	pTrain_Door_System->train_Door_Controller.cse_itf.Trigger_p7_execution_completed = &Cse_Trigger_Train_Door_System_train_Door_Controller_p7_execution_completed;
	/* Read functions */
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p1_modeSelected = &Cse_Read_Train_Door_System_train_Door_Controller_p1_modeSelected;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p2_doorPosition = &Cse_Read_Train_Door_System_train_Door_Controller_p2_doorPosition;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p11_obstructionDetected = &Cse_Read_Train_Door_System_train_Door_Controller_p11_obstructionDetected;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p1_door_status_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p1_door_status_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p1_mode_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p1_mode_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p2_door_status_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p2_door_status_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p2_mode_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p2_mode_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p2_execution_completed = &Cse_Read_Train_Door_System_train_Door_Controller_p2_execution_completed;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p11_door_status_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p11_door_status_change_signal;
	pTrain_Door_System->train_Door_Controller.cse_itf.Read_p11_mode_change_signal = &Cse_Read_Train_Door_System_train_Door_Controller_p11_mode_change_signal;
	/* Server call functions */
	/* END: Train_Door_Controller Cmmunication Interface Configuration */

	/* BEG: Train_Door Communication Interface Configuration */
	/* Write functions */
	/* Trigger functions */
	/* Read functions */
	pTrain_Door_System->train_Door.cse_itf.Read_p5_doorPosition = &Cse_Read_Train_Door_System_train_Door_p5_doorPosition;
	pTrain_Door_System->train_Door.cse_itf.Read_p5_door_status_change_signal = &Cse_Read_Train_Door_System_train_Door_p5_door_status_change_signal;
	pTrain_Door_System->train_Door.cse_itf.Read_p5_mode_change_signal = &Cse_Read_Train_Door_System_train_Door_p5_mode_change_signal;
	pTrain_Door_System->train_Door.cse_itf.Read_p5_execution_completed = &Cse_Read_Train_Door_System_train_Door_p5_execution_completed;
	/* Server call functions */
	/* END: Train_Door Cmmunication Interface Configuration */

	/* BEG: Proximity_Sensor Communication Interface Configuration */
	/* Write functions */
	pTrain_Door_System->proximity_Sensor.cse_itf.Write_p1_obstructionDetected = &Cse_Write_Train_Door_System_proximity_Sensor_p1_obstructionDetected;
	/* Trigger functions */
	pTrain_Door_System->proximity_Sensor.cse_itf.Trigger_p1_door_status_change_signal = &Cse_Trigger_Train_Door_System_proximity_Sensor_p1_door_status_change_signal;
	pTrain_Door_System->proximity_Sensor.cse_itf.Trigger_p1_mode_change_signal = &Cse_Trigger_Train_Door_System_proximity_Sensor_p1_mode_change_signal;
	/* Read functions */
	/* Server call functions */
	/* END: Proximity_Sensor Cmmunication Interface Configuration */

}

/**
 * Function configuring pre-defined tasks.
 * Function to call just after Cse_component_instances_init
 */
void Cse_task_descriptors_init(void) { 
	static function_ptr task0_functions[3];
	static Cse_instance_ptr task0_cseInstances[3];

	/* Runnable to task mapping */
	task0_functions[0] = (function_ptr)&Context_Interaction_Context_Interaction_main;
	task0_cseInstances[0] = &pTrain_Door_System->context_Interaction.cse_itf;

	/* Runnable to task mapping */
	task0_functions[1] = (function_ptr)&Train_Door_Controller_TrainDoorControllerStateMachine_main;
	task0_cseInstances[1] = &pTrain_Door_System->train_Door_Controller.cse_itf;

	/* Runnable to task mapping */
	task0_functions[2] = (function_ptr)&Train_Door_ob_udp_main;
	task0_cseInstances[2] = &pTrain_Door_System->train_Door.cse_itf;

	/* Periodic task task0 configuration */
	task_descriptors[0].type = PERIODIC;
	task_descriptors[0].period = 500;
	task_descriptors[0].functions = task0_functions;
	task_descriptors[0].cse_instances = task0_cseInstances;
	task_descriptors[0].nfunctions = 3;

}

/**
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 */
void Cse_components_init(void) { 
	Train_Door_ob_udp_init(&pTrain_Door_System->train_Door.cse_itf);
	Train_Door_Controller_TrainDoorControllerStateMachine_init(&pTrain_Door_System->train_Door_Controller.cse_itf);
	Context_Interaction_Context_Interaction_init(&pTrain_Door_System->context_Interaction.cse_itf);
}

/** Function calling all the end functions as configured in the model. */
void Cse_components_end(void) { 
}

/* end of file */