/* @date 2026-07-01T10:15:54.865721400Z */

/**********************************************************************************
 * @file Cse_hook_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_HOOK_CFG_H
#define CSE_HOOK_CFG_H

/**********************************************************************************
 * Macros declaration definition
 **********************************************************************************/

/**
 * Define symbol ENABLE_HOOKS to enable the mechanism of hooks 
 * Enabled by default
 */
#define ENABLE_HOOKS
#ifdef ENABLE_HOOKS

#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal
#define Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected
#define Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed
#define Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected
#define Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal
#define Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed

#endif /* ENABLE_HOOKS */

#endif /* CSE_HOOK_CFG_H */

/* end of file */