/* @date 2026-07-01T10:15:54.875050900Z */

/**********************************************************************************
 * @file Cse_hook_usr.c
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version <?VERSION?>
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

/**
 * define symbol USER_HOOKS to enable this file content on compiler 
 * command or uncomment following line
 */
/* #define USER_HOOKS */
#ifdef USER_HOOKS

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Cse_cfg.h"
#include "Cse_hook.h"

#ifdef __cplusplus
/** Code is compiled as C code even if the file is a cpp file */
extern "C" {
#endif /* __cplusplus */

/* BEG_USER_CODE(HEADER) do not remove */
/* Add your includes here */
/* END_USER_CODE(HEADER) do not remove */

/**********************************************************************************
 * Functions implementation
 **********************************************************************************/
 

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Start
 * Start hook to be overwritten to Trigger door status change signal on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data){ 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Return
 * Return hook to be overwritten to Trigger door status change signal on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Start
 * Start hook to be overwritten to Trigger mode change signal on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data){ 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Return
 * Return hook to be overwritten to Trigger mode change signal on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Start
 * Start hook to be overwritten to Trigger door status change signal on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data){ 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Return
 * Return hook to be overwritten to Trigger door status change signal on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Start
 * Start hook to be overwritten to Trigger mode change signal on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data){ 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Return
 * Return hook to be overwritten to Trigger mode change signal on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Start
 * Start hook to be overwritten to Trigger execution completed on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Start(SignalEvent_execution_completed_type* data){ 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Return
 * Return hook to be overwritten to Trigger execution completed on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Start
 * Start hook to be overwritten to Trigger door status change signal on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data){ 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Return
 * Return hook to be overwritten to Trigger door status change signal on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Start
 * Start hook to be overwritten to Trigger mode change signal on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data){ 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Return
 * Return hook to be overwritten to Trigger mode change signal on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Start
 * Start hook to be overwritten to Trigger execution completed on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Start(SignalEvent_execution_completed_type* data){ 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Return
 * Return hook to be overwritten to Trigger execution completed on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Start
 * Start hook to be overwritten to Trigger door status change signal on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data){ 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Return
 * Return hook to be overwritten to Trigger door status change signal on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Start
 * Start hook to be overwritten to Trigger mode change signal on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data){ 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Return
 * Return hook to be overwritten to Trigger mode change signal on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Start
 * Start hook to be overwritten to Trigger execution completed on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Start(SignalEvent_execution_completed_type* data){ 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Return
 * Return hook to be overwritten to Trigger execution completed on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Start
 * Start hook to be overwritten to Trigger execution completed on p7 port
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Start(SignalEvent_execution_completed_type* data){ 
	/* BEG_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Return
 * Return hook to be overwritten to Trigger execution completed on p7 port
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Start
 * Start hook to be overwritten to Trigger door status change signal on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data){ 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Return
 * Return hook to be overwritten to Trigger door status change signal on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}


/**
 * Function Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Start
 * Start hook to be overwritten to Trigger mode change signal on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data){ 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Return
 * Return hook to be overwritten to Trigger mode change signal on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Start
 * Start hook to be overwritten to send modeSelected value on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Start(Integer* data) { 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Return
 * Return hook to be overwritten to send modeSelected value on p1 port
 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Return(Integer* data) { 
	/* BEG_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(8cdecd72-02e3-40ac-a6a8-069f8fb6382c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Start
 * Start hook to be overwritten to send doorPosition value on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Return
 * Return hook to be overwritten to send doorPosition value on p2 port
 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(928df5f2-5631-4950-9761-72d896a3391e_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Start
 * Start hook to be overwritten to send doorPosition value on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Return
 * Return hook to be overwritten to send doorPosition value on p3 port
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(be386dc7-58c6-4c25-8012-7fba412841be_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Start
 * Start hook to be overwritten to send doorPosition value on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Return
 * Return hook to be overwritten to send doorPosition value on p5 port
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a33da647-abe5-41f1-882e-91ddbe59843c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Start
 * Start hook to be overwritten to send responseComputed value on p7 port
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Start(Integer* data) { 
	/* BEG_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Return
 * Return hook to be overwritten to send responseComputed value on p7 port
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Return(Integer* data) { 
	/* BEG_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(c2800b68-86e8-49c4-8a10-2d4246b310d2_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Start
 * Start hook to be overwritten to send obstructionDetected value on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Start(Integer* data) { 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
}

/**
 * Function Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Return
 * Return hook to be overwritten to send obstructionDetected value on p1 port
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Return(Integer* data) { 
	/* BEG_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(59befc0c-bac7-463a-8070-b5c6e97f99e9_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Start
 * Start Hook to be overwritten to read doorPosition value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Return
 * Return Hook to be overwritten to read doorPosition value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Start
 * Start Hook to be overwritten to read responseComputed value on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Start(Integer* data) { 
	/* BEG_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Return
 * Return Hook to be overwritten to read responseComputed value on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Return(Integer* data) { 
	/* BEG_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_54de9d0d-599f-443f-8052-7f6024c39f84) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Start
 * Start Hook to be overwritten to read modeSelected value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Start(Integer* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Return
 * Return Hook to be overwritten to read modeSelected value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Return(Integer* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_b6f93485-a2b6-4080-80f5-10570af329b3) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Start
 * Start Hook to be overwritten to read doorPosition value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Return
 * Return Hook to be overwritten to read doorPosition value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Start
 * Start Hook to be overwritten to read obstructionDetected value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Start(Integer* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Return
 * Return Hook to be overwritten to read obstructionDetected value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Return(Integer* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_800e0afa-8505-4c88-8f35-de8d078cae72) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Start
 * Start Hook to be overwritten to read doorPosition value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Start(Integer* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Return
 * Return Hook to be overwritten to read doorPosition value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Return(Integer* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_e31a8173-c5bb-4741-ae55-4d469e4cafd9) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Start
 * Start Hook to be overwritten to read door status change signal value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Return
 * Return Hook to be overwritten to read door status change signal value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Start
 * Start Hook to be overwritten to read mode change signal value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Return
 * Return Hook to be overwritten to read mode change signal value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Start
 * Start Hook to be overwritten to read execution completed value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Start(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Return
 * Return Hook to be overwritten to read execution completed value on p3 port
 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(38703e60-991e-43b4-bdd8-f193b32f1f34_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Start
 * Start Hook to be overwritten to read execution completed value on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Start(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Return
 * Return Hook to be overwritten to read execution completed value on p7 port
 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(67fd8ba7-80a0-46f9-917a-0f153cd044c8_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Start
 * Start Hook to be overwritten to read door status change signal value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Return
 * Return Hook to be overwritten to read door status change signal value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Start
 * Start Hook to be overwritten to read mode change signal value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Return
 * Return Hook to be overwritten to read mode change signal value on p1 port
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(d200f23f-0e4e-48b0-b9ec-8aa771967b1c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Start
 * Start Hook to be overwritten to read door status change signal value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Return
 * Return Hook to be overwritten to read door status change signal value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Start
 * Start Hook to be overwritten to read mode change signal value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Return
 * Return Hook to be overwritten to read mode change signal value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Start
 * Start Hook to be overwritten to read execution completed value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Start(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Return
 * Return Hook to be overwritten to read execution completed value on p2 port
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(a508c28b-8f08-4791-b0b9-b4e08a7c38fb_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Start
 * Start Hook to be overwritten to read door status change signal value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Return
 * Return Hook to be overwritten to read door status change signal value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Start
 * Start Hook to be overwritten to read mode change signal value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Return
 * Return Hook to be overwritten to read mode change signal value on p11 port
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(93aaeaf6-8332-484b-84a1-6d7d946f65a4_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Start
 * Start Hook to be overwritten to read door status change signal value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Return
 * Return Hook to be overwritten to read door status change signal value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_9f5d5b14-6dad-4d7d-a485-f61a8f31ca89) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Start
 * Start Hook to be overwritten to read mode change signal value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Return
 * Return Hook to be overwritten to read mode change signal value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_0e1623b0-1cca-4739-8ee0-1499a716748c) do not remove */
}
/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Start
 * Start Hook to be overwritten to read execution completed value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Start(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

/**
 * Function Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Return
 * Return Hook to be overwritten to read execution completed value on p5 port
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Return(SignalEvent_execution_completed_type* data) { 
	/* BEG_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
	/* Add your includes here */
	/* END_USER_CODE(3ec770c3-f880-49cf-9bbb-cde69d3c4a2c_6c8c23b9-05f4-4d98-89c0-16313e11afaa) do not remove */
}

#ifdef __cplusplus
}
#endif /* __cplusplus */

/* BEG_USER_CODE(FOOTER) do not remove */
/* Add your includes here */
/* END_USER_CODE(FOOTER) do not remove */

#endif /* USER_HOOKS */
/* end of file */