/* @date 2026-07-01T10:15:54.921605600Z */

/**********************************************************************************
 * @file Cse_cfg.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_CFG_H
#define CSE_CFG_H

#ifdef __cplusplus
extern "C" {
#endif /*  __cplusplus  */

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "task_descriptor.h" /* task_descriptor declaration */

#include "Context_Interaction_type.h"
#include "Train_Door_Controller_type.h"
#include "Train_Door_type.h"
#include "Proximity_Sensor_type.h"

/**********************************************************************************
 * Macros declaration
 **********************************************************************************/

/** Number of predefined tasks */
#define NUMBER_OF_TASKS 1

/**
 * Tasks ids definition &
 * Behaviors in tasks position index definition
 */
#define TASK_0 0

#define TASK_0_context_Interaction_Context_Interaction 0
#define TASK_0_train_Door_Controller_TrainDoorControllerStateMachine 1
#define TASK_0_train_Door_ob_udp 2

/**********************************************************************************
 * Functions declaration
 **********************************************************************************/

/**
 * Map the communication APIs to component instances
 * First function to call before Cse_task_descriptors_init & Cse_components_init
 */
void Cse_component_instances_init(void);

/**
 * Function configuring each task.
 * Function to call just after Cse_component_instances_init
 */
void Cse_task_descriptors_init(void);

/**
 * Function calling all the init functions as configured in the model.
 * To be called after Cse_task_descriptors_init & Cse_component_instances_init
 */
void Cse_components_init(void);

/** Function calling all the end functions as configured in the model. */
void Cse_components_end(void);

/** Extern declaration of task_descriptors variable for its access from the TAL. */
extern task_descriptor task_descriptors[NUMBER_OF_TASKS];

/**********************************************************************************
 * Triggering functions declaration for access from testing infrastructure
 **********************************************************************************/
void Cse_Trigger_Train_Door_System_context_Interaction_p1_door_status_change_signal(void);
void Cse_Trigger_Train_Door_System_context_Interaction_p1_mode_change_signal(void);
void Cse_Trigger_Train_Door_System_context_Interaction_p2_door_status_change_signal(void);
void Cse_Trigger_Train_Door_System_context_Interaction_p2_mode_change_signal(void);
void Cse_Trigger_Train_Door_System_context_Interaction_p2_execution_completed(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_door_status_change_signal(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_mode_change_signal(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p3_execution_completed(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_door_status_change_signal(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_mode_change_signal(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p5_execution_completed(void);
void Cse_Trigger_Train_Door_System_train_Door_Controller_p7_execution_completed(void);
void Cse_Trigger_Train_Door_System_proximity_Sensor_p1_door_status_change_signal(void);
void Cse_Trigger_Train_Door_System_proximity_Sensor_p1_mode_change_signal(void);

#ifdef __cplusplus
} /* extern "C"  */
#endif /* __cplusplus  */

#endif /* CSE_CFG_H  */

/* end of file */