/* @date 2026-07-01T10:15:54.842976Z */

/**********************************************************************************
 * @file Cse_hook.h
 * 
 * Automatically generated by Software Producer Engineer
 * Communication & Scheduling Environment Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 * @reverse_ignore
 **********************************************************************************/

#ifndef CSE_HOOK_H
#define CSE_HOOK_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Cse_hook_cfg.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/**********************************************************************************
 * Functions declaration
 **********************************************************************************/
#if defined(Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal)
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_context_Interaction_p1_door_status_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal)
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_context_Interaction_p1_mode_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal)
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_context_Interaction_p2_door_status_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal)
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_context_Interaction_p2_mode_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed)
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_context_Interaction_p2_execution_completed */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_door_status_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_mode_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p3_execution_completed */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_door_status_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_mode_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p5_execution_completed */

#if defined(Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed)
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_train_Door_Controller_p7_execution_completed */

#if defined(Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal)
extern void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_door_status_change_signal */

#if defined(Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal)
extern void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Start(value)  ((void) (0))
#define Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_TriggerHook_Train_Door_System_proximity_Sensor_p1_mode_change_signal */

#if defined(Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected)
extern void Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_context_Interaction_p1_modeSelected */

#if defined(Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition)
extern void Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_context_Interaction_p2_doorPosition */

#if defined(Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition)
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_train_Door_Controller_p3_doorPosition */

#if defined(Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition)
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_train_Door_Controller_p5_doorPosition */

#if defined(Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed)
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_train_Door_Controller_p7_responseComputed */

#if defined(Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected)
extern void Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Start(Integer* data);
extern void Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Return(Integer* data);
#else
#define Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Start(value)  ((void) (0))
#define Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected_Return(value)  ((void) (0))
#endif /* Cse_WriteHook_Train_Door_System_proximity_Sensor_p1_obstructionDetected */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p3_doorPosition */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p7_responseComputed */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_modeSelected */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_doorPosition */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_obstructionDetected */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition)
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Start(Integer* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Return(Integer* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_p5_doorPosition */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p3_door_status_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p3_mode_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p3_execution_completed */

#if defined(Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed)
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_context_Interaction_p7_execution_completed */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_door_status_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p1_mode_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_door_status_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_mode_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p2_execution_completed */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_door_status_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_Controller_p11_mode_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Start(SignalEvent_door_status_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Return(SignalEvent_door_status_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_p5_door_status_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal)
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Start(SignalEvent_mode_change_signal_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Return(SignalEvent_mode_change_signal_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_p5_mode_change_signal */

#if defined(Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed)
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Start(SignalEvent_execution_completed_type* data);
extern void Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Return(SignalEvent_execution_completed_type* data);
#else
#define Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Start(value)  ((void) (0))
#define Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed_Return(value)  ((void) (0))
#endif /* Cse_ReadHook_Train_Door_System_train_Door_p5_execution_completed */

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CSE_HOOK_H */

/* end of file */