/* @date 2026-07-01T10:15:55.386030900Z */

/**********************************************************************************
 * @file internal_types.h
 * 
 * Automatically generated by Software Production Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from NOT APPLICABLE
 **********************************************************************************/

#ifndef INTERNAL_TYPES_H
#define INTERNAL_TYPES_H

#include <stdbool.h>

/**********************************************************************************
 * Data Type Integer definition
 * @generated_from 5cd7f245-cadf-3400-6880-ebec00028bb6#b8933913-eda4-4531-becb-f3db290affb2
 **********************************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;
#endif /* Integer */


/**********************************************************************************
 * Data Types used in statemachines and activities definition
 **********************************************************************************/

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
/** @reverse_ignore */
typedef bool Boolean; 
#endif

#ifndef Integer_DEFINITION
#define Integer_DEFINITION
/** @reverse_ignore */
typedef int Integer;  
#endif

#ifndef Real_DEFINITION
#define Real_DEFINITION
/** @reverse_ignore */
typedef double Real;  
#endif

#ifndef String_DEFINITION
#define String_DEFINITION
/** @reverse_ignore */
typedef char * String;  
#endif

#ifndef TRUE
/** @reverse_ignore */
#define TRUE true
#endif

#ifndef FALSE
/** @reverse_ignore */
#define FALSE false
#endif

#endif /* #ifndef INTERNAL_TYPES_H */

/* end of file */