/* @date 2026-07-01T10:15:55.364451400Z */

/**********************************************************************************
 * @file Proximity_Sensor_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 **********************************************************************************/

#ifndef PROXIMITY_SENSOR_ITF_H
#define PROXIMITY_SENSOR_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Proximity_Sensor_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/**
	 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
	 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72	
	 */
	void (*Write_p1_obstructionDetected)(Integer* data);

	/* Trigger functions */

	/**
	 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Trigger_p1_door_status_change_signal)(void);

	/**
	 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Trigger_p1_mode_change_signal)(void);

	/* Read functions */

	/* Server call functions */

	/* pointer to parent */
	struct Proximity_Sensor_ *parent;
} Cse_Proximity_Sensor_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/**
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_Write_p1_obstructionDetected(Cse_Proximity_Sensor_Struct* instance, Integer* data);

/* Trigger functions declaration */

/**
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_p1_door_status_change_signal(Cse_Proximity_Sensor_Struct* instance);

/**
 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_p1_mode_change_signal(Cse_Proximity_Sensor_Struct* instance);

/* Read functions declaration */

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Write_p1_obstructionDetected(inst, data) (inst)->Write_p1_obstructionDetected(data)
#define Cse_Trigger_p1_door_status_change_signal(inst) (inst)->Trigger_p1_door_status_change_signal()
#define Cse_Trigger_p1_mode_change_signal(inst) (inst)->Trigger_p1_mode_change_signal()
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* PROXIMITY_SENSOR_ITF_H */

/* end of file */