/* @date 2026-07-01T10:15:55.359922200Z */

/**********************************************************************************
 * @file Proximity_Sensor_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 **********************************************************************************/

#include "Proximity_Sensor.h"
#include "Proximity_Sensor_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
