/* @date 2026-07-01T10:15:55.372971100Z */

/**********************************************************************************
 * @file Proximity_Sensor.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 **********************************************************************************/

#ifndef PROXIMITY_SENSOR_H
#define PROXIMITY_SENSOR_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Proximity_Sensor_itf.h"
#include "internal_types.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Proximity_Sensor_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 */
typedef struct {
} Proximity_Sensor_VTable;

/** @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008 */
typedef struct Proximity_Sensor_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Proximity_Sensor_*);

	/** Pointer to virtual table */
	const Proximity_Sensor_VTable *vtable;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Communication interface
	 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
	 * @reverse_ignore
	 */
	Cse_Proximity_Sensor_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Proximity_Sensor;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 */
void Proximity_Sensor_ctor(Proximity_Sensor* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef PROXIMITY_SENSOR_H */

/* end of file */