/* @date 2026-07-01T10:15:55.359922200Z */

/**********************************************************************************
 * @file Proximity_Sensor_type.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 **********************************************************************************/

#ifndef PROXIMITY_SENSOR_TYPE_H
#define PROXIMITY_SENSOR_TYPE_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h>

/* stdbool.h define standard bool (true/false) starting from C99 standard */
#include <stdbool.h>

/**********************************************************************************
 * Data Type Integer definition
 **********************************************************************************/
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int Integer;    
#endif /* Integer */

/**********************************************************************************
 * Data Type trigger_type definition
 **********************************************************************************/
#ifndef trigger_type_DEFINITION
#define trigger_type_DEFINITION
typedef bool trigger_type;    
#endif /* trigger_type */

/**********************************************************************************
 * Data Type SignalEvent_door_status_change_signal_type definition
 **********************************************************************************/
#ifndef SignalEvent_door_status_change_signal_type_DEFINITION
#define SignalEvent_door_status_change_signal_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_door_status_change_signal_type;    
#endif /* SignalEvent_door_status_change_signal_type */

/**********************************************************************************
 * Data Type SignalEvent_mode_change_signal_type definition
 **********************************************************************************/
#ifndef SignalEvent_mode_change_signal_type_DEFINITION
#define SignalEvent_mode_change_signal_type_DEFINITION
typedef struct {
	trigger_type trigger;
} SignalEvent_mode_change_signal_type;    
#endif /* SignalEvent_mode_change_signal_type */

#endif /* PROXIMITY_SENSOR_TYPE_H */

/* end of file */