/* @date 2026-07-01T10:15:55.378506500Z */

/**********************************************************************************
 * @file Proximity_Sensor.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Proximity_Sensor.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 */
static void Proximity_Sensor_dtor(struct Proximity_Sensor_* self);

/** vtable variable declaration */
static const Proximity_Sensor_VTable vtable_Proximity_Sensor = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 */
void Proximity_Sensor_ctor(Proximity_Sensor* self) {
	/** Init pointer to destructor */
	self->dtor = &Proximity_Sensor_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Proximity_Sensor;

	/** Default values */

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
}

/**
 * Destructor generated automatically
 * @generated_from ae25ff8f-8f4e-468b-8ef7-22fce0606008
 * @reverse_ignore
 */
static void Proximity_Sensor_dtor(struct Proximity_Sensor_* self) {
	/** Call hierarchical destructors */

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */