/* @date 2026-07-01T10:15:55.266478500Z */

/**********************************************************************************
 * @file Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.c
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 * @reverse_ignore
 **********************************************************************************/

/* Application code for activity "ExecutionCompleted" */

#include "Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.h"

#include "Train_Door_Controller.h"
#include <string.h>
/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                         instance->p1_modeSelected
#define p1                                                      p1_modeSelected
#define p2_doorPosition                                         instance->p2_doorPosition
#define p2                                                      p2_doorPosition
#define p3_doorPosition                                         instance->p3_doorPosition
#define p3                                                      p3_doorPosition
#define p5_doorPosition                                         instance->p5_doorPosition
#define p5                                                      p5_doorPosition
#define p7_responseComputed                                     instance->p7_responseComputed
#define p7                                                      p7_responseComputed
#define p11_obstructionDetected                                 instance->p11_obstructionDetected
#define p11                                                     p11_obstructionDetected
#define mode_requested                                          instance->classifier->mode_requested
#define position_requested                                      instance->classifier->position_requested
#define position_current                                        instance->classifier->position_current
#define obstruction_detected                                    instance->classifier->obstruction_detected
#define response_computed                                       instance->classifier->response_computed
#define mode_current                                            instance->classifier->mode_current
#define position_feedback_current                               instance->classifier->position_feedback_current

/**********************************************************************************
 * default event handlers
 **********************************************************************************/
static TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T default_peekEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(const \
    TrainDoorControllerStateMachine_ExecutionCompleted_struct * const instance) {
    return instance->EVENT;
}
static TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T default_nextEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance) {
    (void)instance;
    return TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance, TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************************
 * helpers
 **********************************************************************************/
static inline Boolean isRunning_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(const TrainDoorControllerStateMachine_ExecutionCompleted_struct* \
    const instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************************
 * Function TrainDoorControllerStateMachine_ExecutionCompleted_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
static void TrainDoorControllerStateMachine_ExecutionCompleted_struct_dtor(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
    * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function TrainDoorControllerStateMachine_ExecutionCompleted_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
void TrainDoorControllerStateMachine_ExecutionCompleted_struct_ctor(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
    * const self, struct Train_Door_Controller_* classifier) {
    /* Init pointer to destructor */
    self->dtor = &TrainDoorControllerStateMachine_ExecutionCompleted_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Init Function Pointers */
    self->peekEVENT = &default_peekEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted;
    self->nextEVENT = &default_nextEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted;
    self->sendEVENT = &default_sendEvent_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted;
}
/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_ExecutionCompleted_init
 * Implements activity init code
 * Must be called before step function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_ExecutionCompleted_init(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance) {
    instance->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));


    instance->WALL_CLOCK        = (WALLCLOCK_T_TrainDoorControllerStateMachine_ExecutionCompleted)0;

}

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_ExecutionCompleted
 * Implements activity step function
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
Boolean basic_TrainDoorControllerStateMachine_ExecutionCompleted(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance) {
    /* initialization */
    if(isRunning_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(instance) == FALSE) {
        instance->flow[0] = 1; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    /* node SendSignalAction */
    /* @generated_from 66ea7f01-b5fa-4ce8-b2a0-661b9167c7e6 */
    /* @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa */
    if(1 == (instance->flow[0] & 1)) { /* TST_FLOW<-InitialNode */
        Boolean success = instance->sendEVENT(instance, TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_execution_completed);
        if(success != FALSE) {
            instance->flow[0] ^= 1; /* CLR_FLOW<-InitialNode */
            instance->flow[0] |= 2; /* SET_FLOW->ActivityFinalNode */
        }
    }
    /* node ActivityFinalNode */
    /* @generated_from e0fed1d5-bfcf-4ee5-a8a5-bbdeec5a3e5b */
    if(2 == (instance->flow[0] & 2)) { /* TST_FLOW<-SendSignalAction */
        (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));
    }

    return (FALSE == isRunning_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted(instance)) ? TRUE \
        : FALSE;
}

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_ExecutionCompleted_end
 * Implements activity exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_ExecutionCompleted_end(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance) {
    (void)instance;
}

/* end of file */
