/* @date 2026-07-01T10:15:55.304174300Z */

/**********************************************************************************
 * @file Train_Door_Controller.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 **********************************************************************************/

#ifndef TRAIN_DOOR_CONTROLLER_H
#define TRAIN_DOOR_CONTROLLER_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Train_Door_Controller_itf.h"
#include "internal_types.h"
#include "Train_Door_Controller_TrainDoorControllerStateMachine.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Train_Door_Controller_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 */
typedef struct {
} Train_Door_Controller_VTable;

/** @generated_from 4f497378-9e93-4522-a692-869c5025a8eb */
typedef struct Train_Door_Controller_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Train_Door_Controller_*);

	/** Pointer to virtual table */
	const Train_Door_Controller_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Integer:mode_requested
	 * @generated_from 5b78e7ba-958b-4f2e-ad0a-584e1db7e2fc
	 */
	Integer mode_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_requested
	 * @generated_from aef5d082-1f1f-49a7-a703-9d342cc622f8
	 */
	Integer position_requested;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_current
	 * @generated_from 84a00a50-9a15-4034-b55a-9005c7bb1a45
	 */
	Integer position_current;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:obstruction_detected
	 * @generated_from 3a2c2e3c-b1d6-457f-98cb-d090f88dddab
	 */
	Integer obstruction_detected;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:response_computed
	 * @generated_from 872ca7bc-5412-4f8c-900f-0d7623c9db98
	 */
	Integer response_computed;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:mode_current
	 * @generated_from 2fedc32e-72a5-486e-b8c6-7e243acf95cc
	 */
	Integer mode_current;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_feedback_current
	 * @generated_from 99417219-301a-4b9c-8a23-7fc45d10d208
	 */
	Integer position_feedback_current;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_feedback_current
	 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
	 * @reverse_ignore
	 */
	TrainDoorControllerStateMachine_struct Train_Door_Controller_TrainDoorControllerStateMachine;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Public attribute for composition relation to Integer:position_feedback_current
	 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
	 * @reverse_ignore
	 */
	Cse_Train_Door_Controller_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Train_Door_Controller;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 */
void Train_Door_Controller_ctor(Train_Door_Controller* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef TRAIN_DOOR_CONTROLLER_H */

/* end of file */