/* @date 2026-07-01T10:15:55.332306500Z */

/**********************************************************************************
 * @file Train_Door_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 **********************************************************************************/

#include "Train_Door.h"
#include "Train_Door_itf.h"
#include "Tal.h" // tal_getTime

/* end of file */
