/* @date 2026-07-01T10:15:55.275999900Z */

/**********************************************************************************
 * @file Train_Door_Controller_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 **********************************************************************************/

#ifndef TRAIN_DOOR_CONTROLLER_ITF_H
#define TRAIN_DOOR_CONTROLLER_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Train_Door_Controller_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/**
	 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9	
	 */
	void (*Write_p3_doorPosition)(Integer* data);

	/**
	 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9	
	 */
	void (*Write_p5_doorPosition)(Integer* data);

	/**
	 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
	 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84	
	 */
	void (*Write_p7_responseComputed)(Integer* data);

	/* Trigger functions */

	/**
	 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Trigger_p3_door_status_change_signal)(void);

	/**
	 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Trigger_p3_mode_change_signal)(void);

	/**
	 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Trigger_p3_execution_completed)(void);

	/**
	 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Trigger_p5_door_status_change_signal)(void);

	/**
	 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Trigger_p5_mode_change_signal)(void);

	/**
	 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Trigger_p5_execution_completed)(void);

	/**
	 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Trigger_p7_execution_completed)(void);

	/* Read functions */

	/**
	 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
	 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
	 */
	void (*Read_p1_modeSelected)(Integer* data);

	/**
	 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Read_p1_door_status_change_signal)(SignalEvent_door_status_change_signal_type* data);

	/**
	 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Read_p1_mode_change_signal)(SignalEvent_mode_change_signal_type* data);

	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 */
	void (*Read_p2_doorPosition)(Integer* data);

	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Read_p2_door_status_change_signal)(SignalEvent_door_status_change_signal_type* data);

	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Read_p2_mode_change_signal)(SignalEvent_mode_change_signal_type* data);

	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Read_p2_execution_completed)(SignalEvent_execution_completed_type* data);

	/**
	 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
	 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
	 */
	void (*Read_p11_obstructionDetected)(Integer* data);

	/**
	 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Read_p11_door_status_change_signal)(SignalEvent_door_status_change_signal_type* data);

	/**
	 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Read_p11_mode_change_signal)(SignalEvent_mode_change_signal_type* data);

	/* Server call functions */

	/* pointer to parent */
	struct Train_Door_Controller_ *parent;
} Cse_Train_Door_Controller_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

/** @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e */
void Train_Door_Controller_TrainDoorControllerStateMachine_init(Cse_Train_Door_Controller_Struct* instance);
void Train_Door_Controller_TrainDoorControllerStateMachine_main(Cse_Train_Door_Controller_Struct* instance);
void Train_Door_Controller_TrainDoorControllerStateMachine_end(Cse_Train_Door_Controller_Struct* instance);

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/**
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Write_p3_doorPosition(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/**
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Write_p5_doorPosition(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/**
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
 */
void Cse_Write_p7_responseComputed(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/* Trigger functions declaration */

/**
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_p3_door_status_change_signal(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_p3_mode_change_signal(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_p3_execution_completed(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Trigger_p5_door_status_change_signal(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Trigger_p5_mode_change_signal(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_p5_execution_completed(Cse_Train_Door_Controller_Struct* instance);

/**
 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Trigger_p7_execution_completed(Cse_Train_Door_Controller_Struct* instance);

/* Read functions declaration */

/**
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
 */
void Cse_Read_p1_modeSelected(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/**
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Read_p1_door_status_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_door_status_change_signal_type* data);

/**
 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Read_p1_mode_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_mode_change_signal_type* data);

/**
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Read_p2_doorPosition(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/**
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Read_p2_door_status_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_door_status_change_signal_type* data);

/**
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Read_p2_mode_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_mode_change_signal_type* data);

/**
 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Read_p2_execution_completed(Cse_Train_Door_Controller_Struct* instance, SignalEvent_execution_completed_type* data);

/**
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
 */
void Cse_Read_p11_obstructionDetected(Cse_Train_Door_Controller_Struct* instance, Integer* data);

/**
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Read_p11_door_status_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_door_status_change_signal_type* data);

/**
 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Read_p11_mode_change_signal(Cse_Train_Door_Controller_Struct* instance, SignalEvent_mode_change_signal_type* data);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Write_p3_doorPosition(inst, data) (inst)->Write_p3_doorPosition(data)
#define Cse_Write_p5_doorPosition(inst, data) (inst)->Write_p5_doorPosition(data)
#define Cse_Write_p7_responseComputed(inst, data) (inst)->Write_p7_responseComputed(data)
#define Cse_Trigger_p3_door_status_change_signal(inst) (inst)->Trigger_p3_door_status_change_signal()
#define Cse_Trigger_p3_mode_change_signal(inst) (inst)->Trigger_p3_mode_change_signal()
#define Cse_Trigger_p3_execution_completed(inst) (inst)->Trigger_p3_execution_completed()
#define Cse_Trigger_p5_door_status_change_signal(inst) (inst)->Trigger_p5_door_status_change_signal()
#define Cse_Trigger_p5_mode_change_signal(inst) (inst)->Trigger_p5_mode_change_signal()
#define Cse_Trigger_p5_execution_completed(inst) (inst)->Trigger_p5_execution_completed()
#define Cse_Trigger_p7_execution_completed(inst) (inst)->Trigger_p7_execution_completed()
#define Cse_Read_p1_modeSelected(inst, data) (inst)->Read_p1_modeSelected(data)
#define Cse_Read_p1_door_status_change_signal(inst, data) (inst)->Read_p1_door_status_change_signal(data)
#define Cse_Read_p1_mode_change_signal(inst, data) (inst)->Read_p1_mode_change_signal(data)
#define Cse_Read_p2_doorPosition(inst, data) (inst)->Read_p2_doorPosition(data)
#define Cse_Read_p2_door_status_change_signal(inst, data) (inst)->Read_p2_door_status_change_signal(data)
#define Cse_Read_p2_mode_change_signal(inst, data) (inst)->Read_p2_mode_change_signal(data)
#define Cse_Read_p2_execution_completed(inst, data) (inst)->Read_p2_execution_completed(data)
#define Cse_Read_p11_obstructionDetected(inst, data) (inst)->Read_p11_obstructionDetected(data)
#define Cse_Read_p11_door_status_change_signal(inst, data) (inst)->Read_p11_door_status_change_signal(data)
#define Cse_Read_p11_mode_change_signal(inst, data) (inst)->Read_p11_mode_change_signal(data)
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* TRAIN_DOOR_CONTROLLER_ITF_H */

/* end of file */