/* @date 2026-07-01T10:15:55.346363300Z */

/**********************************************************************************
 * @file Train_Door.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 **********************************************************************************/

#ifndef TRAIN_DOOR_H
#define TRAIN_DOOR_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Train_Door_itf.h"
#include "internal_types.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Train_Door_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 */
typedef struct {
} Train_Door_VTable;

/** @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead */
typedef struct Train_Door_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Train_Door_*);

	/** Pointer to virtual table */
	const Train_Door_VTable *vtable;

	/**********************************************************************************
	 * Communication Interface section
	 **********************************************************************************/
	/**
	 * @generated_brief Communication interface
	 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
	 * @reverse_ignore
	 */
	Cse_Train_Door_Struct cse_itf;

	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Train_Door;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 */
void Train_Door_ctor(Train_Door* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef TRAIN_DOOR_H */

/* end of file */