/* @date 2026-07-01T10:15:54.994889300Z */

/**********************************************************************************
 * @file Train_Door_System.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Train_Door_System.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 * @reverse_ignore
 */
static void Train_Door_System_dtor(struct Train_Door_System_* self);

/** vtable variable declaration */
static const Train_Door_System_VTable vtable_Train_Door_System = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 * @reverse_ignore
 */
void Train_Door_System_ctor(Train_Door_System* self) {
	/** Init pointer to destructor */
	self->dtor = &Train_Door_System_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Train_Door_System;

	/** Default values */

	/** Call hierarchical constructors */
	Context_Interaction_ctor(&self->context_Interaction);
	Train_Door_Controller_ctor(&self->train_Door_Controller);
	Train_Door_ctor(&self->train_Door);
	Proximity_Sensor_ctor(&self->proximity_Sensor);
}

/**
 * Destructor generated automatically
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 * @reverse_ignore
 */
static void Train_Door_System_dtor(struct Train_Door_System_* self) {
	/** Call hierarchical destructors */
	self->context_Interaction.dtor(&self->context_Interaction);
	self->train_Door_Controller.dtor(&self->train_Door_Controller);
	self->train_Door.dtor(&self->train_Door);
	self->proximity_Sensor.dtor(&self->proximity_Sensor);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */