/* @date 2026-07-01T10:15:55.337832300Z */

/**********************************************************************************
 * @file Train_Door_itf.h
 * 
 * Automatically generated by Software Producer Engineer
 * Interface Generator @version v1.0.0
 * 
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 **********************************************************************************/

#ifndef TRAIN_DOOR_ITF_H
#define TRAIN_DOOR_ITF_H

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "Train_Door_type.h"


/**********************************************************************************
 * Interface Structure declaration
 **********************************************************************************/
typedef struct {
	/* Write functions */

	/* Trigger functions */

	/* Read functions */

	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 */
	void (*Read_p5_doorPosition)(Integer* data);

	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 */
	void (*Read_p5_door_status_change_signal)(SignalEvent_door_status_change_signal_type* data);

	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 */
	void (*Read_p5_mode_change_signal)(SignalEvent_mode_change_signal_type* data);

	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 */
	void (*Read_p5_execution_completed)(SignalEvent_execution_completed_type* data);

	/* Server call functions */

	/* pointer to parent */
	struct Train_Door_ *parent;
} Cse_Train_Door_Struct;

/**********************************************************************************
 * Behavior functions declaration
 **********************************************************************************/

/** @generated_from 383655f3-7aac-45e7-9480-1e177db34f91 */
void Train_Door_ob_udp_init(Cse_Train_Door_Struct* instance);
void Train_Door_ob_udp_main(Cse_Train_Door_Struct* instance);
void Train_Door_ob_udp_end(Cse_Train_Door_Struct* instance);

#ifndef CSE_C

#ifdef CSE_CONTRACT
/**********************************************************************************
 * Interfaces functions declaration for documentation purpose
 **********************************************************************************/
/* Write functions declaration */

/* Trigger functions declaration */

/* Read functions declaration */

/**
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
 */
void Cse_Read_p5_doorPosition(Cse_Train_Door_Struct* instance, Integer* data);

/**
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
 */
void Cse_Read_p5_door_status_change_signal(Cse_Train_Door_Struct* instance, SignalEvent_door_status_change_signal_type* data);

/**
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
 */
void Cse_Read_p5_mode_change_signal(Cse_Train_Door_Struct* instance, SignalEvent_mode_change_signal_type* data);

/**
 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
 */
void Cse_Read_p5_execution_completed(Cse_Train_Door_Struct* instance, SignalEvent_execution_completed_type* data);

/* Server call functions declaration */

#else /* #ifdef CSE_CONTRACT */

/**********************************************************************************
 * Interfaces functions mapping used during compilation
 **********************************************************************************/
#define Cse_Read_p5_doorPosition(inst, data) (inst)->Read_p5_doorPosition(data)
#define Cse_Read_p5_door_status_change_signal(inst, data) (inst)->Read_p5_door_status_change_signal(data)
#define Cse_Read_p5_mode_change_signal(inst, data) (inst)->Read_p5_mode_change_signal(data)
#define Cse_Read_p5_execution_completed(inst, data) (inst)->Read_p5_execution_completed(data)
#endif /* #ifdef CSE_CONTRACT */

#endif /* #ifndef CSE_C */

#endif /* TRAIN_DOOR_ITF_H */

/* end of file */