/* @date 2026-07-01T10:15:55.251873700Z */

/**********************************************************************************
 * @file Train_Door_Controller_TrainDoorControllerStateMachine_usr.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 * @reverse_ignore
 **********************************************************************************/

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "Train_Door_Controller_TrainDoorControllerStateMachine.h"
#include "Train_Door_Controller.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                     instance->p1_modeSelected
#define p1                                                  p1_modeSelected
#define p2_doorPosition                                     instance->p2_doorPosition
#define p2                                                  p2_doorPosition
#define p3_doorPosition                                     instance->p3_doorPosition
#define p3                                                  p3_doorPosition
#define p5_doorPosition                                     instance->p5_doorPosition
#define p5                                                  p5_doorPosition
#define p7_responseComputed                                 instance->p7_responseComputed
#define p7                                                  p7_responseComputed
#define p11_obstructionDetected                             instance->p11_obstructionDetected
#define p11                                                 p11_obstructionDetected
#define mode_requested                                      instance->classifier->mode_requested
#define position_requested                                  instance->classifier->position_requested
#define position_current                                    instance->classifier->position_current
#define obstruction_detected                                instance->classifier->obstruction_detected
#define response_computed                                   instance->classifier->response_computed
#define mode_current                                        instance->classifier->mode_current
#define position_feedback_current                           instance->classifier->position_feedback_current

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Closed_Entry_1(...)                              TrainDoorControllerStateMachine_Closed_Entry_1(__VA_ARGS__)
#define GO_resp_Entry_1(...)                             TrainDoorControllerStateMachine_GO_resp_Entry_1(__VA_ARGS__)
#define MAINT_resp_Entry_1(...)                          TrainDoorControllerStateMachine_MAINT_resp_Entry_1(__VA_ARGS__)
#define Maintentance_Entry_1(...)                        TrainDoorControllerStateMachine_Maintentance_Entry_1(__VA_ARGS__)
#define Mode_Set_Entry_1(...)                            TrainDoorControllerStateMachine_Mode_Set_Entry_1(__VA_ARGS__)
#define Obstruction_Detected_Entry_1(...)                TrainDoorControllerStateMachine_Obstruction_Detected_Entry_1(__VA_ARGS__)
#define Open_Entry_1(...)                                TrainDoorControllerStateMachine_Open_Entry_1(__VA_ARGS__)
#define Send_Exec_Terminated_Do_1(...)                   TrainDoorControllerStateMachine_Send_Exec_Terminated_Do_1(__VA_ARGS__)
#define Send_Exec_Terminated_Entry_1(...)                TrainDoorControllerStateMachine_Send_Exec_Terminated_Entry_1(__VA_ARGS__)

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Function Closed_Entry
 * Implements "Entry" of State: Closed
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 71812b5c-7505-4a60-93e4-8ef6de572fe7
 * @generated_from e4aa658e-f6ce-4364-af6f-7b090af007c4
 **********************************************************************************/
void Closed_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entrye4aa658e-f6ce-4364-af6f-7b090af007c4) do not remove */


    /* END_USER_CODE(Entrye4aa658e-f6ce-4364-af6f-7b090af007c4) do not remove */
    position_current=0;
    response_computed=0;
}

/**********************************************************************************
 * Function GO_resp_Entry
 * Implements "Entry" of State: GO resp
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 95cad99e-ff1d-4f18-8f47-6cb72fb61370
 * @generated_from 41c68b82-8855-4b83-92ec-6dabe2278a2c
 **********************************************************************************/
void GO_resp_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entry41c68b82-8855-4b83-92ec-6dabe2278a2c) do not remove */


    /* END_USER_CODE(Entry41c68b82-8855-4b83-92ec-6dabe2278a2c) do not remove */
    response_computed=position_current;
}

/**********************************************************************************
 * Function MAINT_resp_Entry
 * Implements "Entry" of State: MAINT resp
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 26fa4af9-c6db-41ca-b500-7002d91e160d
 * @generated_from dcfac472-eae5-4002-9b80-99d924632378
 **********************************************************************************/
void MAINT_resp_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entrydcfac472-eae5-4002-9b80-99d924632378) do not remove */


    /* END_USER_CODE(Entrydcfac472-eae5-4002-9b80-99d924632378) do not remove */
    response_computed=2;
}

/**********************************************************************************
 * Function Maintentance_Entry
 * Implements "Entry" of State: Maintentance
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c8eb62fa-9649-4a0d-97c9-01e42516a369
 * @generated_from 491656df-60ce-4f26-aa11-6c116758f156
 **********************************************************************************/
void Maintentance_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entry491656df-60ce-4f26-aa11-6c116758f156) do not remove */


    /* END_USER_CODE(Entry491656df-60ce-4f26-aa11-6c116758f156) do not remove */
    response_computed=2;
}

/**********************************************************************************
 * Function Mode_Set_Entry
 * Implements "Entry" of State: Mode Set
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c0209452-fd85-43a1-a08d-48957fd96798
 * @generated_from df243083-c84b-4320-b62b-61702e6e730d
 **********************************************************************************/
void Mode_Set_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entrydf243083-c84b-4320-b62b-61702e6e730d) do not remove */


    /* END_USER_CODE(Entrydf243083-c84b-4320-b62b-61702e6e730d) do not remove */
    mode_current = mode_requested;
}

/**********************************************************************************
 * Function Obstruction_Detected_Entry
 * Implements "Entry" of State: Obstruction Detected
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from dc6f692f-ad83-4203-9007-d4bddfc3031d
 * @generated_from 0126ab83-dca5-4441-9827-d3563726665a
 **********************************************************************************/
void Obstruction_Detected_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entry0126ab83-dca5-4441-9827-d3563726665a) do not remove */


    /* END_USER_CODE(Entry0126ab83-dca5-4441-9827-d3563726665a) do not remove */
    response_computed=3;
}

/**********************************************************************************
 * Function Open_Entry
 * Implements "Entry" of State: Open
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from dc2ca058-86aa-4587-bfe9-a2d91038e56d
 * @generated_from eef57aba-5fc5-45b7-8f0d-499ccf038f4e
 **********************************************************************************/
void Open_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entryeef57aba-5fc5-45b7-8f0d-499ccf038f4e) do not remove */


    /* END_USER_CODE(Entryeef57aba-5fc5-45b7-8f0d-499ccf038f4e) do not remove */
    position_current=1;
    response_computed=1;
}

/**********************************************************************************
 * Function Send_Exec_Terminated_Do
 * Implements "Do" of State: Send Exec Terminated
 * Do calls Activity: ExecutionCompleted
 *
 * @generated_from c58a2eb7-c5d4-4c35-bec0-b88a4110bfe3
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
void Send_Exec_Terminated_Do_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Do98c2cbfb-e91e-47d4-a20e-af2496f1579b) do not remove */


    /* END_USER_CODE(Do98c2cbfb-e91e-47d4-a20e-af2496f1579b) do not remove */
    instance->DONE_ACTIVITY = basic_TrainDoorControllerStateMachine_ExecutionCompleted(&(instance->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted));
}

/**********************************************************************************
 * Function Send_Exec_Terminated_Entry
 * Implements "Entry" of State: Send Exec Terminated
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c58a2eb7-c5d4-4c35-bec0-b88a4110bfe3
 * @generated_from 2f0897da-e754-4a21-9b6f-c80e63117e6b
 **********************************************************************************/
void Send_Exec_Terminated_Entry_1(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(Entry2f0897da-e754-4a21-9b6f-c80e63117e6b) do not remove */


    /* END_USER_CODE(Entry2f0897da-e754-4a21-9b6f-c80e63117e6b) do not remove */
    position_feedback_current = position_current;
}

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void TrainDoorControllerStateMachine_user_init(TrainDoorControllerStateMachine_struct *instance) {

    /* BEG_USER_CODE(init_state_machine) do not remove */

    /* do whatever needed */
    (void)instance;

    /* END_USER_CODE(init_state_machine) do not remove */
}

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void TrainDoorControllerStateMachine_user_end(TrainDoorControllerStateMachine_struct *instance) {
    /* BEG_USER_CODE(end_state_machine) do not remove */

    /* do whatever needed */

    /* END_USER_CODE(end_state_machine) do not remove */
    basic_TrainDoorControllerStateMachine_ExecutionCompleted_end(&(instance->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted));
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

/* end of file */
