/* @date 2026-07-01T10:15:54.943041300Z */

/**********************************************************************************
 * @file Train_Door_System.h
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 **********************************************************************************/

#ifndef TRAIN_DOOR_SYSTEM_H
#define TRAIN_DOOR_SYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include "internal_types.h"
#include "Proximity_Sensor.h"
#include "Train_Door_Controller.h"
#include "Train_Door.h"
#include "Context_Interaction.h"
 
/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Type definition
 **********************************************************************************/

/** Forward declaration */
struct Train_Door_System_;

/**
 * virtual table definition for const and fct pointer defined in ROM
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 */
typedef struct {
} Train_Door_System_VTable;

/** @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b */
typedef struct Train_Door_System_ {
	/** Function pointer to destructor function generated automatically */
	void (*dtor)(struct Train_Door_System_*);

	/** Pointer to virtual table */
	const Train_Door_System_VTable *vtable;

	/**
	 * @generated_brief Public attribute for composition relation to Context_Interaction:context Interaction
	 * @generated_from b478b07a-2191-4dac-92cc-b0e2aa4a36e6
	 */
	struct Context_Interaction_ context_Interaction;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Train_Door_Controller:train Door Controller
	 * @generated_from 93534809-9a66-462e-8604-8d1d46571c03
	 */
	struct Train_Door_Controller_ train_Door_Controller;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Train_Door:train Door
	 * @generated_from 6b5ffbf3-0c61-42a2-9766-09f66e81ae5e
	 */
	struct Train_Door_ train_Door;  
		
	/**
	 * @generated_brief Public attribute for composition relation to Proximity_Sensor:proximity Sensor
	 * @generated_from a93259fd-06c5-493c-8692-58c52ebd4ff7
	 */
	struct Proximity_Sensor_ proximity_Sensor;  
		
	/**********************************************************************************
	 * Communication & Scheduling Environment - Shared variables declaration
	 **********************************************************************************/
	/**
	 * @generated_from 8cdecd72-02e3-40ac-a6a8-069f8fb6382c
	 * @generated_from b6f93485-a2b6-4080-80f5-10570af329b3
	 * @generated_from 4fbc8aaa-f655-4f57-b27e-6744b0dbc099
	 * @reverse_ignore
	 */
	Integer from_context_Interaction_p1_modeSelected;
	 
	/**
	 * @generated_from 928df5f2-5631-4950-9761-72d896a3391e
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 * @generated_from 795b4412-637e-441e-adb5-c8fcea6acbf3
	 * @reverse_ignore
	 */
	Integer from_context_Interaction_p2_doorPosition;
	 
	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 * @generated_from fd00d1ff-136c-4d08-84c6-aae133c6cd0d
	 * @reverse_ignore
	 */
	SignalEvent_door_status_change_signal_type to_context_Interaction_p3_door_status_change_signal;
	 
	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 * @generated_from fd00d1ff-136c-4d08-84c6-aae133c6cd0d
	 * @reverse_ignore
	 */
	SignalEvent_mode_change_signal_type to_context_Interaction_p3_mode_change_signal;
	 
	/**
	 * @generated_from 38703e60-991e-43b4-bdd8-f193b32f1f34
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 * @generated_from fd00d1ff-136c-4d08-84c6-aae133c6cd0d
	 * @reverse_ignore
	 */
	SignalEvent_execution_completed_type to_context_Interaction_p3_execution_completed;
	 
	/**
	 * @generated_from 67fd8ba7-80a0-46f9-917a-0f153cd044c8
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 * @generated_from c9050b78-7bf1-4f86-b929-9c92bd4a04c5
	 * @reverse_ignore
	 */
	SignalEvent_execution_completed_type to_context_Interaction_p7_execution_completed;
	 
	/**
	 * @generated_from be386dc7-58c6-4c25-8012-7fba412841be
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 * @generated_from 1c4c1a14-3274-4eaf-8605-19ddc1755fa3
	 * @reverse_ignore
	 */
	Integer from_train_Door_Controller_p3_doorPosition;
	 
	/**
	 * @generated_from a33da647-abe5-41f1-882e-91ddbe59843c
	 * @generated_from e31a8173-c5bb-4741-ae55-4d469e4cafd9
	 * @generated_from d198951c-84f5-4f35-bc9a-dd205f9fb201
	 * @reverse_ignore
	 */
	Integer from_train_Door_Controller_p5_doorPosition;
	 
	/**
	 * @generated_from c2800b68-86e8-49c4-8a10-2d4246b310d2
	 * @generated_from 54de9d0d-599f-443f-8052-7f6024c39f84
	 * @generated_from aed8f2f0-3f1f-415c-8122-c2ef9f3c8623
	 * @reverse_ignore
	 */
	Integer from_train_Door_Controller_p7_responseComputed;
	 
	/**
	 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 * @generated_from f702d1d4-7490-4070-a614-bbd6d6d9ffd0
	 * @reverse_ignore
	 */
	SignalEvent_door_status_change_signal_type to_train_Door_Controller_p1_door_status_change_signal;
	 
	/**
	 * @generated_from d200f23f-0e4e-48b0-b9ec-8aa771967b1c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 * @generated_from f702d1d4-7490-4070-a614-bbd6d6d9ffd0
	 * @reverse_ignore
	 */
	SignalEvent_mode_change_signal_type to_train_Door_Controller_p1_mode_change_signal;
	 
	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 * @generated_from ef4990df-7d69-4108-b0ad-643d22d09ec9
	 * @reverse_ignore
	 */
	SignalEvent_door_status_change_signal_type to_train_Door_Controller_p2_door_status_change_signal;
	 
	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 * @generated_from ef4990df-7d69-4108-b0ad-643d22d09ec9
	 * @reverse_ignore
	 */
	SignalEvent_mode_change_signal_type to_train_Door_Controller_p2_mode_change_signal;
	 
	/**
	 * @generated_from a508c28b-8f08-4791-b0b9-b4e08a7c38fb
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 * @generated_from ef4990df-7d69-4108-b0ad-643d22d09ec9
	 * @reverse_ignore
	 */
	SignalEvent_execution_completed_type to_train_Door_Controller_p2_execution_completed;
	 
	/**
	 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 * @generated_from 07f75fc3-5397-4874-ba7e-f2b0257813ed
	 * @reverse_ignore
	 */
	SignalEvent_door_status_change_signal_type to_train_Door_Controller_p11_door_status_change_signal;
	 
	/**
	 * @generated_from 93aaeaf6-8332-484b-84a1-6d7d946f65a4
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 * @generated_from 07f75fc3-5397-4874-ba7e-f2b0257813ed
	 * @reverse_ignore
	 */
	SignalEvent_mode_change_signal_type to_train_Door_Controller_p11_mode_change_signal;
	 
	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89
	 * @generated_from 9faed9f4-a367-49eb-b781-9249fae8267a
	 * @reverse_ignore
	 */
	SignalEvent_door_status_change_signal_type to_train_Door_p5_door_status_change_signal;
	 
	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c
	 * @generated_from 9faed9f4-a367-49eb-b781-9249fae8267a
	 * @reverse_ignore
	 */
	SignalEvent_mode_change_signal_type to_train_Door_p5_mode_change_signal;
	 
	/**
	 * @generated_from 3ec770c3-f880-49cf-9bbb-cde69d3c4a2c
	 * @generated_from 6c8c23b9-05f4-4d98-89c0-16313e11afaa
	 * @generated_from 9faed9f4-a367-49eb-b781-9249fae8267a
	 * @reverse_ignore
	 */
	SignalEvent_execution_completed_type to_train_Door_p5_execution_completed;
	 
	/**
	 * @generated_from 59befc0c-bac7-463a-8070-b5c6e97f99e9
	 * @generated_from 800e0afa-8505-4c88-8f35-de8d078cae72
	 * @generated_from 3e456a4e-6512-4413-81d9-b2f5c66ff8c0
	 * @reverse_ignore
	 */
	Integer from_proximity_Sensor_p1_obstructionDetected;
	 
	/* BEG_USER_CODE(user_section) do not remove */
	/* Declare your attributes and methods here */
	/* END_USER_CODE(user_section) do not remove */
} Train_Door_System;

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 664c1add-8c35-4a8a-bbd8-c693eab35c3b
 * @reverse_ignore
 */
void Train_Door_System_ctor(Train_Door_System* self);

#ifdef __cplusplus
}
#endif

#endif /* #ifndef TRAIN_DOOR_SYSTEM_H */

/* end of file */