/* @date 2026-07-01T10:15:55.241042Z */

/**********************************************************************************
 * @file Train_Door_Controller_TrainDoorControllerStateMachine.c
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 * @reverse_ignore
 **********************************************************************************/

/* Application code for statemachine "TrainDoorControllerStateMachine" */

/**********************************************************************************
 * Includes
 **********************************************************************************/
#include "Train_Door_Controller_TrainDoorControllerStateMachine.h"
#include "Train_Door_Controller.h"

/**********************************************************************************
 * Alias to variables
 **********************************************************************************/
#define p1_modeSelected                                     instance->p1_modeSelected
#define p1                                                  p1_modeSelected
#define p2_doorPosition                                     instance->p2_doorPosition
#define p2                                                  p2_doorPosition
#define p3_doorPosition                                     instance->p3_doorPosition
#define p3                                                  p3_doorPosition
#define p5_doorPosition                                     instance->p5_doorPosition
#define p5                                                  p5_doorPosition
#define p7_responseComputed                                 instance->p7_responseComputed
#define p7                                                  p7_responseComputed
#define p11_obstructionDetected                             instance->p11_obstructionDetected
#define p11                                                 p11_obstructionDetected
#define mode_requested                                      instance->classifier->mode_requested
#define position_requested                                  instance->classifier->position_requested
#define position_current                                    instance->classifier->position_current
#define obstruction_detected                                instance->classifier->obstruction_detected
#define response_computed                                   instance->classifier->response_computed
#define mode_current                                        instance->classifier->mode_current
#define position_feedback_current                           instance->classifier->position_feedback_current

/**********************************************************************************
 * Macros for user modifiable behaviors mapping
 **********************************************************************************/
#define Closed_Entry_1(...)                              TrainDoorControllerStateMachine_Closed_Entry_1(__VA_ARGS__)
#define GO_resp_Entry_1(...)                             TrainDoorControllerStateMachine_GO_resp_Entry_1(__VA_ARGS__)
#define MAINT_resp_Entry_1(...)                          TrainDoorControllerStateMachine_MAINT_resp_Entry_1(__VA_ARGS__)
#define Maintentance_Entry_1(...)                        TrainDoorControllerStateMachine_Maintentance_Entry_1(__VA_ARGS__)
#define Mode_Set_Entry_1(...)                            TrainDoorControllerStateMachine_Mode_Set_Entry_1(__VA_ARGS__)
#define Obstruction_Detected_Entry_1(...)                TrainDoorControllerStateMachine_Obstruction_Detected_Entry_1(__VA_ARGS__)
#define Open_Entry_1(...)                                TrainDoorControllerStateMachine_Open_Entry_1(__VA_ARGS__)
#define Send_Exec_Terminated_Do_1(...)                   TrainDoorControllerStateMachine_Send_Exec_Terminated_Do_1(__VA_ARGS__)
#define Send_Exec_Terminated_Entry_1(...)                TrainDoorControllerStateMachine_Send_Exec_Terminated_Entry_1(__VA_ARGS__)

/**********************************************************************************
 * Function TrainDoorControllerStateMachine_struct_dtor
 * Destructor generated automatically to clean data structure
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
static void TrainDoorControllerStateMachine_struct_dtor(struct TrainDoorControllerStateMachine_struct * const self) {
    /* Clean pointer to destructor */
    self->dtor = NULL;
}
/**********************************************************************************
 * Function TrainDoorControllerStateMachine_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void TrainDoorControllerStateMachine_struct_ctor(struct TrainDoorControllerStateMachine_struct * const self, struct Train_Door_Controller_* \
    classifier) {
    /* Init pointer to destructor */
    self->dtor = &TrainDoorControllerStateMachine_struct_dtor;

    /* Init Classifier variable */
    self->classifier = classifier;

    /* Call hierarchical constructors */
    TrainDoorControllerStateMachine_ExecutionCompleted_struct_ctor(&self->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted, \
        classifier);
}
/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_init
 * Implements statemachine init code
 * Must be called before main loop function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_init(TrainDoorControllerStateMachine_struct *instance) {
    instance->FIRST = TRUE;
    instance->WALL_CLOCK = (WALLCLOCK_T_Train_Door_Controller)0;
    instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID;
    instance->CURRENT_STATE_1 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID;
    instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID;

    basic_TrainDoorControllerStateMachine_ExecutionCompleted_init(&(instance->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted));

    TrainDoorControllerStateMachine_user_init(instance);
}

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine
 * Implements statemachine main loop
 * Must be called after init function
 * Generated automatically. Do not edit content.
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine(TrainDoorControllerStateMachine_struct *instance) {
    if(instance->FIRST != FALSE) {
        instance->FIRST = FALSE;
        /* Transition INITIAL_0 -> Idle */
        /* @generated_from 2043241e-1ff5-4d61-bf5a-68fc738ef853 */
        instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Idle;
    }
    switch(instance->CURRENT_STATE_0) {
        /* State Idle */
        /* @generated_from 2002b994-62f5-42e4-8dea-b0358db8c219 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Idle: {
            if( instance->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_mode_change_signal ) {
                /* Transition Idle -> Mode Set */
                /* @generated_from 69ac090e-0533-47b7-8e7f-7ec31ec65fdc */
                /* @generated_from 65014332-c9bb-4ca8-9b76-b247e5858708 */
                Mode_Set_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Mode_Set */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Mode_Set;
                instance->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT;
            } else if( (instance->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal)
            &&  (mode_current==0) ) {
                /* Transition Idle -> GO */
                /* @generated_from 7d90e987-f746-44ce-a4b2-2dceec301da8 */
                /* @generated_from 7d6588f5-2bc2-4b10-a213-287884fae522 */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO;
                instance->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT;
            } else if( (instance->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal)
            &&  (mode_current==1) ) {
                /* Transition Idle -> Maintentance */
                /* @generated_from e5fe5a6f-a670-46ec-8274-198bb1423b12 */
                /* @generated_from da922946-b4a5-4aed-885b-60a964d316af */
                Maintentance_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Maintentance */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Maintentance;
                instance->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Idle */
        }
        /* State Mode Set */
        /* @generated_from c0209452-fd85-43a1-a08d-48957fd96798 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Mode_Set: {
            if( mode_requested==0 ) {
                /* Transition Mode Set -> GO resp */
                /* @generated_from 6d5fd8fd-1dbd-40e6-95d7-d3d8f81a5dfb */
                GO_resp_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO_resp */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO_resp;
            } else if( mode_requested==1 ) {
                /* Transition Mode Set -> MAINT resp */
                /* @generated_from accc1b38-6234-4dad-b55f-bc0adcae08be */
                MAINT_resp_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_MAINT_resp */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_MAINT_resp;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Mode_Set */
        }
        /* State Exec Terminated */
        /* @generated_from 3a3d6e54-ccad-400f-9693-913c6447bfd5 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated: {
            if( (instance->WALL_CLOCK - instance->ENTER_CLOCK_0) >= (WALLCLOCK_T_Train_Door_Controller)2 ) {
                /* Transition Exec Terminated -> Send Exec Terminated */
                /* @generated_from a28855dd-6673-4d63-a51e-4dbcfb609bd7 */
                /* @generated_from 1e0a3ae0-19c9-4133-b1d1-f6dd57b757f0 */
                Send_Exec_Terminated_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Send_Exec_Terminated */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Send_Exec_Terminated;
                instance->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated */
        }
        /* State GO */
        /* @generated_from 82bffc77-e722-46a0-99a9-d190dcc87542 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO: {
            if( position_requested==0 ) {
                /* Transition GO -> TrainDoorControllerStateMachine_no_name_1 */
                /* @generated_from 32a117b8-1112-4394-8527-f12bfebbb3d6 */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_1;
                /* Transition INITIAL_2 -> Closing */
                /* @generated_from 86644e75-1bfe-42d8-88bb-6911e42892bb */
                instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closing;
            } else if( position_requested==1 ) {
                /* Transition GO -> TrainDoorControllerStateMachine_no_name_0 */
                /* @generated_from a0ef87d6-2d6d-4b7e-9578-40c271fb7621 */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_0;
                /* Transition INITIAL_1 -> Opening */
                /* @generated_from 27da4799-8759-4000-9ea4-68180da77312 */
                instance->CURRENT_STATE_1 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Opening;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO */
        }
        /* State TrainDoorControllerStateMachine_no_name_0 */
        /* @generated_from 175fa031-3617-407a-86e3-50885d202ac2 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_0: {
            switch(instance->CURRENT_STATE_1) {
                /* State Open */
                /* @generated_from dc2ca058-86aa-4587-bfe9-a2d91038e56d */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Open: {
                    /* Transition Open -> FINAL_1 */
                    /* @generated_from 9966cdfa-9683-4297-9f1a-15c3653e7251 */
                    instance->CURRENT_STATE_1 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_1;
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Open */
                }
                /* State Opening */
                /* @generated_from 076d1189-4f28-4ee6-aa0f-e3b695beb7b8 */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Opening: {
                    /* Transition Opening -> Open */
                    /* @generated_from b3f775c1-9909-41a7-825d-393a5eb2eb55 */
                    Open_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Open */
                    instance->CURRENT_STATE_1 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Open;
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Opening */
                }
                /* State FINAL_1 */
                /* @generated_from 42aedf1f-d808-4d9a-96ca-94e440023164 */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_1: {
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_1 */
                }
                default: break;
            } /* end of switch */
            if( (instance->CURRENT_STATE_1 == TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_1) || (instance->CURRENT_STATE_1 \
                == TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID) ) {
                /* Transition TrainDoorControllerStateMachine_no_name_0 -> Exec Terminated */
                /* @generated_from 57758999-8fda-4e8f-b3de-ac60cb180bb6 */
                instance->CURRENT_STATE_1 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID;
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_0 */
        }
        /* State TrainDoorControllerStateMachine_no_name_1 */
        /* @generated_from 6019af50-6319-434a-a131-ec16d9725413 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_1: {
            switch(instance->CURRENT_STATE_2) {
                /* State Obstruction Detected */
                /* @generated_from dc6f692f-ad83-4203-9007-d4bddfc3031d */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Obstruction_Detected: {
                    /* Transition Obstruction Detected -> FINAL_2 */
                    /* @generated_from 94429d3d-b06d-4e18-9d74-79315f4a7172 */
                    instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2;
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Obstruction_Detected */
                }
                /* State Closing */
                /* @generated_from 93d18821-3c51-4149-a199-80d69688a7fa */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closing: {
                    if( obstruction_detected==0 ) {
                        /* Transition Closing -> Closed */
                        /* @generated_from 8b5dfa3e-f7d7-4dae-873c-c189e2a7e85d */
                        Closed_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closed */
                        instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closed;
                    } else if( obstruction_detected==1 ) {
                        /* Transition Closing -> Obstruction Detected */
                        /* @generated_from ea7ffa03-546e-4f34-9dd2-66ea7807a523 */
                        Obstruction_Detected_Entry_1(instance); /* Entry of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Obstruction_Detected */
                        instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Obstruction_Detected;
                    } else {
                        /* stay in th state */;
                    }
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closing */
                }
                /* State Closed */
                /* @generated_from 71812b5c-7505-4a60-93e4-8ef6de572fe7 */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closed: {
                    /* Transition Closed -> FINAL_2 */
                    /* @generated_from 0117bc93-9654-4cad-9ccb-00635cb27bb7 */
                    instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2;
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closed */
                }
                /* State FINAL_2 */
                /* @generated_from 2724174f-2622-4e14-b114-d1a3912c67e1 */
                case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2: {
                    break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2 */
                }
                default: break;
            } /* end of switch */
            if( (instance->CURRENT_STATE_2 == TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2) || (instance->CURRENT_STATE_2 \
                == TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID) ) {
                /* Transition TrainDoorControllerStateMachine_no_name_1 -> Exec Terminated */
                /* @generated_from be82920c-d0cf-47b0-a997-e8d9739de9af */
                instance->CURRENT_STATE_2 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID;
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated;
                instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_1 */
        }
        /* State Send Exec Terminated */
        /* @generated_from c58a2eb7-c5d4-4c35-bec0-b88a4110bfe3 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Send_Exec_Terminated: {
            instance->DONE_ACTIVITY = TRUE;
            Send_Exec_Terminated_Do_1(instance); /* Do ExecutionCompleted */
            if(instance->DONE_ACTIVITY != FALSE) {
                /* Transition Send Exec Terminated -> Idle */
                /* @generated_from d1bd35e0-abea-4fab-a2d6-cc53a8f18aaf */
                instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Idle;
            } else {
                /* stay in th state */;
            }
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Send_Exec_Terminated */
        }
        /* State Maintentance */
        /* @generated_from c8eb62fa-9649-4a0d-97c9-01e42516a369 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Maintentance: {
            /* Transition Maintentance -> Exec Terminated */
            /* @generated_from 92e4a47f-27dc-4ac9-aa91-600d8ea27585 */
            instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated;
            instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Maintentance */
        }
        /* State MAINT resp */
        /* @generated_from 26fa4af9-c6db-41ca-b500-7002d91e160d */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_MAINT_resp: {
            /* Transition MAINT resp -> Exec Terminated */
            /* @generated_from ad881438-9be8-4254-9828-b8e6e9016257 */
            instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated;
            instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_MAINT_resp */
        }
        /* State GO resp */
        /* @generated_from 95cad99e-ff1d-4f18-8f47-6cb72fb61370 */
        case TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO_resp: {
            /* Transition GO resp -> Exec Terminated */
            /* @generated_from 6d31e74f-a1e6-4d7b-a160-a725c3aab84f */
            instance->CURRENT_STATE_0 = TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated;
            instance->ENTER_CLOCK_0 = instance->WALL_CLOCK;
            break; /* end of TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO_resp */
        }
        default: break;
    } /* end of switch */
}

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_end
 * Implements statemachine exit code
 * Generated automatically. Do not edit content.
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_end(TrainDoorControllerStateMachine_struct *instance) {
    TrainDoorControllerStateMachine_user_end(instance);
}

/* end of file */
