/* @date 2026-07-01T10:15:55.261475900Z */

/**********************************************************************************
 * @file Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.h
 *
 * Automatically generated by Software Production Engineer
 * Activity Code Generator @version v1.0.0
 *
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 * @reverse_ignore
 **********************************************************************************/

#ifndef TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_H
#define TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_H

#include "Train_Door_Controller_type.h" /* Datatypes for internal data */
#include "internal_types.h" /* Datatypes for internal data */

#include <stdint.h>
typedef enum {
    TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_NO_EVENT,
    TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_execution_completed
} TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T;

#ifndef ESP_TYPES_TrainDoorControllerStateMachine_ExecutionCompleted
#define ESP_TYPES_TrainDoorControllerStateMachine_ExecutionCompleted
typedef double  WALLCLOCK_T_TrainDoorControllerStateMachine_ExecutionCompleted;  /* time type (can be any scalar) */
typedef void *  USERDATA_T_TrainDoorControllerStateMachine_ExecutionCompleted;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_*);

    /* user data */
    USERDATA_T_TrainDoorControllerStateMachine_ExecutionCompleted   USERDATA;

    /* data */

    Integer                                                         p1_modeSelected;
    Integer                                                         p2_doorPosition;
    Integer                                                         p3_doorPosition;
    Integer                                                         p5_doorPosition;
    Integer                                                         p7_responseComputed;
    Integer                                                         p11_obstructionDetected;



    /* events */
    TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T      EVENT;
    TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T      (*peekEVENT)(const struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
        * const instance); /* returns the first event in the event-queue or NO_EVENT when empty */
    TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T      (*nextEVENT)(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
        *instance); /* removes the first event in the event-queue  and returns the new first one or NO_EVENT if empty */
    Boolean                                                         (*sendEVENT)(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
        *instance, TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T event); /* send an event in the queue. Returns false if this can't be done (e.g. queue is full), and true otherwise. */

    /* pointer to classifier class */
    struct Train_Door_Controller_* classifier;

    /* internal */
    uint32_t                                                        flow[1];

    WALLCLOCK_T_TrainDoorControllerStateMachine_ExecutionCompleted  WALL_CLOCK;
} TrainDoorControllerStateMachine_ExecutionCompleted_struct;

void TrainDoorControllerStateMachine_ExecutionCompleted_struct_ctor(struct TrainDoorControllerStateMachine_ExecutionCompleted_struct_ \
    * const self, struct Train_Door_Controller_* classifier);
void basic_TrainDoorControllerStateMachine_ExecutionCompleted_init(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance);
Boolean basic_TrainDoorControllerStateMachine_ExecutionCompleted(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance);
void basic_TrainDoorControllerStateMachine_ExecutionCompleted_end(TrainDoorControllerStateMachine_ExecutionCompleted_struct \
    *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_H*/
/* end of file */
