/* @date 2026-07-01T10:15:55.234028900Z */

/**********************************************************************************
 * @file Train_Door_Controller_TrainDoorControllerStateMachine.h
 *
 * Automatically generated by Software Production Engineer
 * Statemachine Code Generator @version v1.0.0
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 * @reverse_ignore
 **********************************************************************************/

#ifndef TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_H
#define TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_H

#include <stdint.h>
#include "Train_Door_Controller_itf.h" /* Datatypes defined at interfaces */
#include "internal_types.h" /* Datatypes for internal data */

#include "Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.h"

#ifndef WALLCLOCK_T_Train_Door_Controller
#define WALLCLOCK_T_Train_Door_Controller   WALLCLOCK_T_Train_Door_Controller
typedef double  WALLCLOCK_T_Train_Door_Controller;  /* time type (can be any scalar) */
#endif
#ifndef USERDATA_T_Train_Door_Controller
#define USERDATA_T_Train_Door_Controller    USERDATA_T_Train_Door_Controller
typedef void *  USERDATA_T_Train_Door_Controller;   /* replace this pointer by an anonymous struct if needed. */
#endif

typedef enum {
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_INITIAL_0,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Idle,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Mode_Set,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Exec_Terminated,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_0,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_TrainDoorControllerStateMachine_no_name_1,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Send_Exec_Terminated,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Maintentance,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_MAINT_resp,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_GO_resp,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Open,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Opening,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_INITIAL_1,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_1,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Obstruction_Detected,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closing,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_Closed,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_INITIAL_2,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_FINAL_2,
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T_VOID
} TRAINDOORCONTROLLERSTATEMACHINE_STATE_T;

typedef enum {
    TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal,
    TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_mode_change_signal,
    TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT
} TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T;

typedef struct TrainDoorControllerStateMachine_struct {
    /* Function pointer to destructor function generated automatically */
    void (*dtor)(struct TrainDoorControllerStateMachine_struct*);

    /* user data */
    USERDATA_T_Train_Door_Controller                            USERDATA;


    /* data */
    Integer                                                     p1_modeSelected;
    Integer                                                     p2_doorPosition;
    Integer                                                     p3_doorPosition;
    Integer                                                     p5_doorPosition;
    Integer                                                     p7_responseComputed;
    Integer                                                     p11_obstructionDetected;


    /* sub behaviors */
    TrainDoorControllerStateMachine_ExecutionCompleted_struct   Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted;

    /* pointer to classifier */
    struct Train_Door_Controller_                            *  classifier;

    /* Region states */
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T                     CURRENT_STATE_0;
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T                     CURRENT_STATE_1;
    TRAINDOORCONTROLLERSTATEMACHINE_STATE_T                     CURRENT_STATE_2;

    /* Main clock */
    WALLCLOCK_T_Train_Door_Controller                           WALL_CLOCK;

    /* Time event clocks */
    WALLCLOCK_T_Train_Door_Controller                           ENTER_CLOCK_0;

    TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T                     EVENT;
    Boolean                                                     FIRST;
    Boolean                                                     DONE_ACTIVITY;
} TrainDoorControllerStateMachine_struct;

/**********************************************************************************
 * Function TrainDoorControllerStateMachine_struct_ctor
 * Constructor generated automatically to initialize data structure
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void TrainDoorControllerStateMachine_struct_ctor(struct TrainDoorControllerStateMachine_struct * const self, struct Train_Door_Controller_* \
    classifier);

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_init
 * Implements statemachine init code
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_init(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine
 * Implements statemachine main loop
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function basic_TrainDoorControllerStateMachine_end
 * Implements statemachine exit code
 *
 * @generated_from 313750c3-00a9-4569-8587-cffbd4e3773e
 **********************************************************************************/
void basic_TrainDoorControllerStateMachine_end(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Closed_Entry
 * Implements "Entry" of State: Closed
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 71812b5c-7505-4a60-93e4-8ef6de572fe7
 * @generated_from e4aa658e-f6ce-4364-af6f-7b090af007c4
 **********************************************************************************/
void TrainDoorControllerStateMachine_Closed_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function GO_resp_Entry
 * Implements "Entry" of State: GO resp
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 95cad99e-ff1d-4f18-8f47-6cb72fb61370
 * @generated_from 41c68b82-8855-4b83-92ec-6dabe2278a2c
 **********************************************************************************/
void TrainDoorControllerStateMachine_GO_resp_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function MAINT_resp_Entry
 * Implements "Entry" of State: MAINT resp
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from 26fa4af9-c6db-41ca-b500-7002d91e160d
 * @generated_from dcfac472-eae5-4002-9b80-99d924632378
 **********************************************************************************/
void TrainDoorControllerStateMachine_MAINT_resp_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Maintentance_Entry
 * Implements "Entry" of State: Maintentance
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c8eb62fa-9649-4a0d-97c9-01e42516a369
 * @generated_from 491656df-60ce-4f26-aa11-6c116758f156
 **********************************************************************************/
void TrainDoorControllerStateMachine_Maintentance_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Mode_Set_Entry
 * Implements "Entry" of State: Mode Set
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c0209452-fd85-43a1-a08d-48957fd96798
 * @generated_from df243083-c84b-4320-b62b-61702e6e730d
 **********************************************************************************/
void TrainDoorControllerStateMachine_Mode_Set_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Obstruction_Detected_Entry
 * Implements "Entry" of State: Obstruction Detected
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from dc6f692f-ad83-4203-9007-d4bddfc3031d
 * @generated_from 0126ab83-dca5-4441-9827-d3563726665a
 **********************************************************************************/
void TrainDoorControllerStateMachine_Obstruction_Detected_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Open_Entry
 * Implements "Entry" of State: Open
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from dc2ca058-86aa-4587-bfe9-a2d91038e56d
 * @generated_from eef57aba-5fc5-45b7-8f0d-499ccf038f4e
 **********************************************************************************/
void TrainDoorControllerStateMachine_Open_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Send_Exec_Terminated_Do
 * Implements "Do" of State: Send Exec Terminated
 * Do calls Activity: ExecutionCompleted
 *
 * @generated_from c58a2eb7-c5d4-4c35-bec0-b88a4110bfe3
 * @generated_from 98c2cbfb-e91e-47d4-a20e-af2496f1579b
 **********************************************************************************/
void TrainDoorControllerStateMachine_Send_Exec_Terminated_Do_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * Function Send_Exec_Terminated_Entry
 * Implements "Entry" of State: Send Exec Terminated
 * Entry calls OpaqueBehavior: null
 *
 * @generated_from c58a2eb7-c5d4-4c35-bec0-b88a4110bfe3
 * @generated_from 2f0897da-e754-4a21-9b6f-c80e63117e6b
 **********************************************************************************/
void TrainDoorControllerStateMachine_Send_Exec_Terminated_Entry_1(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * User specific init function
 **********************************************************************************/
void TrainDoorControllerStateMachine_user_init(TrainDoorControllerStateMachine_struct *instance);

/**********************************************************************************
 * User specific end function
 **********************************************************************************/
void TrainDoorControllerStateMachine_user_end(TrainDoorControllerStateMachine_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TRAIN_DOOR_CONTROLLER_TRAINDOORCONTROLLERSTATEMACHINE_H*/
/* end of file */
