/* @date 2026-07-01T10:15:55.272986100Z */

/**********************************************************************************
 * @file Train_Door_Controller_itf.c
 *
 * Automatically generated by Software Production Engineer
 * Interface Code Generator @version v1.0.0
 *
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 **********************************************************************************/

#include "Train_Door_Controller.h"
#include "Train_Door_Controller_itf.h"
#include "Train_Door_Controller_TrainDoorControllerStateMachine.h"
#include "Tal.h" // tal_getTime

/**********************************************************************************
 * Init function invoked for component initialization purpose.
 **********************************************************************************/
void Train_Door_Controller_TrainDoorControllerStateMachine_init(Cse_Train_Door_Controller_Struct* instance) {
    /* Get component Train Door Controller from "parent" */
    Train_Door_Controller *pTrain_Door_Controller = instance->parent;

    /* Get behavior train_Door_Controller_TrainDoorControllerStateMachine from the Train Door Controller */
    TrainDoorControllerStateMachine_struct *train_Door_Controller_TrainDoorControllerStateMachine = &pTrain_Door_Controller->Train_Door_Controller_TrainDoorControllerStateMachine;


    /* Initialization job which can be done in a separated function or inlined. */
    basic_TrainDoorControllerStateMachine_init(train_Door_Controller_TrainDoorControllerStateMachine);
}

/**********************************************************************************
 * Main function Body of behavior "Train_Door_Controller_TrainDoorControllerStateMachine"
 **********************************************************************************/
void Train_Door_Controller_TrainDoorControllerStateMachine_main(Cse_Train_Door_Controller_Struct* instance) {
    /* Get component Train Door Controller from "parent" */
    Train_Door_Controller *pTrain_Door_Controller = instance->parent;

    /* Get behavior train_Door_Controller_TrainDoorControllerStateMachine from the Train Door Controller */
    TrainDoorControllerStateMachine_struct *train_Door_Controller_TrainDoorControllerStateMachine = &pTrain_Door_Controller->Train_Door_Controller_TrainDoorControllerStateMachine;

    /* read input(s) */
    Cse_Read_p1_modeSelected(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p1_modeSelected);
    Cse_Read_p2_doorPosition(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p2_doorPosition);
    Cse_Read_p11_obstructionDetected(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p11_obstructionDetected);

    /* handle external event(s) */
    train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT;
    {
        /* @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89 */
        SignalEvent_door_status_change_signal_type signalEvent_door_status_change_signal;
        Cse_Read_p1_door_status_change_signal(instance, &signalEvent_door_status_change_signal);
        if(signalEvent_door_status_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal;
        }
    }
    if(train_Door_Controller_TrainDoorControllerStateMachine->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT) \
        {
        /* @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c */
        SignalEvent_mode_change_signal_type signalEvent_mode_change_signal;
        Cse_Read_p1_mode_change_signal(instance, &signalEvent_mode_change_signal);
        if(signalEvent_mode_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_mode_change_signal;
        }
    }
    if(train_Door_Controller_TrainDoorControllerStateMachine->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT) \
        {
        /* @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89 */
        SignalEvent_door_status_change_signal_type signalEvent_door_status_change_signal;
        Cse_Read_p2_door_status_change_signal(instance, &signalEvent_door_status_change_signal);
        if(signalEvent_door_status_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal;
        }
    }
    if(train_Door_Controller_TrainDoorControllerStateMachine->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT) \
        {
        /* @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c */
        SignalEvent_mode_change_signal_type signalEvent_mode_change_signal;
        Cse_Read_p2_mode_change_signal(instance, &signalEvent_mode_change_signal);
        if(signalEvent_mode_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_mode_change_signal;
        }
    }
    if(train_Door_Controller_TrainDoorControllerStateMachine->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT) \
        {
        /* @generated_from 9f5d5b14-6dad-4d7d-a485-f61a8f31ca89 */
        SignalEvent_door_status_change_signal_type signalEvent_door_status_change_signal;
        Cse_Read_p11_door_status_change_signal(instance, &signalEvent_door_status_change_signal);
        if(signalEvent_door_status_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_door_status_change_signal;
        }
    }
    if(train_Door_Controller_TrainDoorControllerStateMachine->EVENT == TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_NO_EVENT) \
        {
        /* @generated_from 0e1623b0-1cca-4739-8ee0-1499a716748c */
        SignalEvent_mode_change_signal_type signalEvent_mode_change_signal;
        Cse_Read_p11_mode_change_signal(instance, &signalEvent_mode_change_signal);
        if(signalEvent_mode_change_signal.trigger == TRUE) {
            train_Door_Controller_TrainDoorControllerStateMachine->EVENT = TRAINDOORCONTROLLERSTATEMACHINE_EVENT_T_mode_change_signal;
        }
    }
    /* handle internal event (s) */

    /* update WALL_CLOCK */
    train_Door_Controller_TrainDoorControllerStateMachine->WALL_CLOCK = tal_GetTime();
    train_Door_Controller_TrainDoorControllerStateMachine->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.WALL_CLOCK \
        = tal_GetTime();

    /* Copy data in */
    pTrain_Door_Controller->mode_requested = train_Door_Controller_TrainDoorControllerStateMachine->p1_modeSelected;
    pTrain_Door_Controller->position_requested = train_Door_Controller_TrainDoorControllerStateMachine->p2_doorPosition;
    pTrain_Door_Controller->obstruction_detected = train_Door_Controller_TrainDoorControllerStateMachine->p11_obstructionDetected;

    (void)basic_TrainDoorControllerStateMachine(train_Door_Controller_TrainDoorControllerStateMachine);

    /* Copy data out */
    train_Door_Controller_TrainDoorControllerStateMachine->p5_doorPosition = pTrain_Door_Controller->position_current;
    train_Door_Controller_TrainDoorControllerStateMachine->p7_responseComputed = pTrain_Door_Controller->response_computed;
    train_Door_Controller_TrainDoorControllerStateMachine->p3_doorPosition = pTrain_Door_Controller->position_feedback_current;

    /* write output(s) */
    Cse_Write_p3_doorPosition(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p3_doorPosition);
    Cse_Write_p5_doorPosition(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p5_doorPosition);
    Cse_Write_p7_responseComputed(instance, &train_Door_Controller_TrainDoorControllerStateMachine->p7_responseComputed);

    /* trigger event(s) */
    if (train_Door_Controller_TrainDoorControllerStateMachine->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.EVENT \
        == TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_execution_completed) {
        train_Door_Controller_TrainDoorControllerStateMachine->Send_Exec_Terminated_Do_1_Train_Door_Controller_TrainDoorControllerStateMachine_ExecutionCompleted.EVENT \
            = TRAINDOORCONTROLLERSTATEMACHINE_EXECUTIONCOMPLETED_EVENT_T_NO_EVENT;
        Cse_Trigger_p7_execution_completed(instance);
    }
}

/**********************************************************************************
 * Exit function invoked at execution ending
 **********************************************************************************/
void Train_Door_Controller_TrainDoorControllerStateMachine_end(Cse_Train_Door_Controller_Struct* instance) {
    /* Get component Train Door Controller from "parent" */
    Train_Door_Controller *pTrain_Door_Controller = instance->parent;

    /* Get behavior train_Door_Controller_TrainDoorControllerStateMachine from the Train Door Controller */
    TrainDoorControllerStateMachine_struct *train_Door_Controller_TrainDoorControllerStateMachine = &pTrain_Door_Controller->Train_Door_Controller_TrainDoorControllerStateMachine;

    basic_TrainDoorControllerStateMachine_end(train_Door_Controller_TrainDoorControllerStateMachine);
}

/* end of file */
