/* @date 2026-07-01T10:15:55.351890100Z */

/**********************************************************************************
 * @file Train_Door.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Train_Door.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 */
static void Train_Door_dtor(struct Train_Door_* self);

/** vtable variable declaration */
static const Train_Door_VTable vtable_Train_Door = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 */
void Train_Door_ctor(Train_Door* self) {
	/** Init pointer to destructor */
	self->dtor = &Train_Door_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Train_Door;

	/** Default values */

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
}

/**
 * Destructor generated automatically
 * @generated_from 9d20e555-15dd-4331-8ad3-93b39c9d7ead
 * @reverse_ignore
 */
static void Train_Door_dtor(struct Train_Door_* self) {
	/** Call hierarchical destructors */

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */