/* @date 2026-07-01T10:15:55.313233600Z */

/**********************************************************************************
 * @file Train_Door_Controller.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Classes Code Generator @version v1.0.0
 * 
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 **********************************************************************************/

/**********************************************************************************
 * Includes declaration
 **********************************************************************************/
#include <stddef.h> /* for NULL declaration */
#include "Train_Door_Controller.h"



/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**********************************************************************************
 * Local Members Declaration 
 **********************************************************************************/

/**
 * Destructor declaration
 * Generated automatically
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 */
static void Train_Door_Controller_dtor(struct Train_Door_Controller_* self);

/** vtable variable declaration */
static const Train_Door_Controller_VTable vtable_Train_Door_Controller = {   
};

/**********************************************************************************
 * Functions Implementation
 **********************************************************************************/

/**
 * Constructor generated automatically to initialize data structure
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 */
void Train_Door_Controller_ctor(Train_Door_Controller* self) {
	/** Init pointer to destructor */
	self->dtor = &Train_Door_Controller_dtor;
	/** Init pointer to virtual table */
	self->vtable = &vtable_Train_Door_Controller;

	/** Default values */
	self->mode_requested = 0;
	self->position_requested = 0;
	self->position_current = 0;
	self->obstruction_detected = 0;
	self->response_computed = 0;
	self->mode_current = 0;
	self->position_feedback_current = 0;

	/** Configure Communication Interface */
	self->cse_itf.parent = self;

	/** Call hierarchical constructors */
	TrainDoorControllerStateMachine_struct_ctor(&self->Train_Door_Controller_TrainDoorControllerStateMachine, self);
}

/**
 * Destructor generated automatically
 * @generated_from 4f497378-9e93-4522-a692-869c5025a8eb
 * @reverse_ignore
 */
static void Train_Door_Controller_dtor(struct Train_Door_Controller_* self) {
	/** Call hierarchical destructors */
	self->Train_Door_Controller_TrainDoorControllerStateMachine.dtor(&self->Train_Door_Controller_TrainDoorControllerStateMachine);

	/** Clean pointer to destructor */
	self->dtor = NULL;
}

/* BEG_USER_CODE(user_implementation_section) do not remove */
/* Add your methods here */
/* END_USER_CODE(user_implementation_section) do not remove */

/* end of file */