/* @date 2026-07-01T10:15:55.325296800Z */

/**********************************************************************************
 * @file Train_Door_ob_udp.c
 * 
 * Automatically generated by Software Producer Engineer
 * UML Opaque Behavior C/C++ Code Generator @version v1.0.0
 **********************************************************************************/
#include "Train_Door.h"


/* BEG_USER_CODE(header) do not remove */
/* Add your includes here */
/* END_USER_CODE(header) do not remove */

/**
 * Start of Opaque Behavior ob_udp body section
 * @generated_from 383655f3-7aac-45e7-9480-1e177db34f91
 */


/* BEG_USER_CODE(383655f3-7aac-45e7-9480-1e177db34f91) do not remove */

#include <stdint.h>

#include <winsock2.h>
#include <ws2tcpip.h>

#include "Tal.h"

#define SERVER_IP   "127.0.0.1"   // destination IP
#define SERVER_PORT 8844          // destination port

WSADATA wsa;
SOCKET sock;
struct sockaddr_in server_addr;


void *kbnThread(void *arg)
{
    // Initialize Winsock
    if (WSAStartup(MAKEWORD(2,2), &wsa) != 0) {
        tal_printf("WSAStartup failed\n");
        return NULL;
    }

    // Create UDP socket
    sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (sock == INVALID_SOCKET) {
        tal_printf("Socket creation failed\n");
        WSACleanup();
        return NULL;
    }

    // Configure server address (localhost)
    memset(&server_addr, 0, sizeof(server_addr));
    server_addr.sin_family = AF_INET;
    server_addr.sin_port = htons(SERVER_PORT);
    inet_pton(AF_INET, SERVER_IP, &server_addr.sin_addr);

    return NULL;
}


void Train_Door_ob_udp_init(Cse_Train_Door_Struct* self)
{
    tal_CreateThread(kbnThread, NULL);
}


void Train_Door_ob_udp_main(Cse_Train_Door_Struct* self)
{
    int sent;
        
    int value;
    // Send only one integer (axis 1 with offset)
    Cse_Read_p5_doorPosition(self, &value);



    // Convert to network byte order
    //int32_t netValue = htonl(value);

    sent = sendto(sock,
                  (const char *)&value,
                  sizeof(value),
                  0,
                  (struct sockaddr *)&server_addr,
                  sizeof(server_addr));

    if (sent == SOCKET_ERROR) {
        tal_printf("sendto failed\n");
    }
}


void Train_Door_ob_udp_end(Cse_Train_Door_Struct* self)
{
    if (sock != INVALID_SOCKET) {
        closesocket(sock);
    }

    WSACleanup();
}

/* END_USER_CODE(383655f3-7aac-45e7-9480-1e177db34f91) do not remove */
/* End of Opaque Behavior ob_udp body section */

/* end of file */